### ISSUE TITLE
[YSQL] Failed test org.yb.pgsql.TestPgRegressHashIndex.testPgRegressHashIndex

### ISSUE THREAD

**Issue by pilshchikov** [yugabyte/yugabyte-db#10453]
Jira Link: [DB-1206](https://yugabyte.atlassian.net/browse/DB-1206)
### Description

|  commit  |  pass/failed/runs  |  pass %  |
|  ------  |  -------  |  -------  |
|  0fb5dc5  |  9/1/10  |  90%  |
|  d9b0de9  |  0/10/10  |  0%  |

@kneeraj hi, looks like after your commit test testPgRegressHashIndex starts failing on the regular base

**Comment by kneeraj** [comment]
The underlying issue may be: https://github.com/yugabyte/yugabyte-db/issues/10894 and fixed by PR: https://github.com/yugabyte/pgjdbc/pull/4

Will raise the phabricator diff as soon as the above PR is approved

**Comment by bmatican** [comment]
Seems this test still fails in 3/25 commits. Not enough to show up in the default view, but wanted to call out. @kneeraj were you able to push that through in the end & confirm if all good after?

Details: https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&build_type=all&class=org.yb.pgsql.TestPgRegressHashIndex&fail_tag=all&name=testPgRegressHashIndex&platform=linux
