### ISSUE TITLE
[DocDB] FlushJobTest unit test fails in tsan runs.

### ISSUE THREAD

**Issue by rthallamko3** [yugabyte/yugabyte-db#11254]
Jira Link: [DB-3359](https://yugabyte.atlassian.net/browse/DB-3359)
### Description

Data from the test run [stability](https://detective-gcp.dev.yugabyte.com/stability?num_commits=25): 

Number | Test | Fail % | Number of recent failures | Commit Fail % | Number of failed commits
8 | FlushJobTest.Empty | 28.9 | 22 | 88.0 | 22

Failure logs:

```
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0127 01:44:37.633656 17717 flush_job.cc:156] [default] No eligible memtables to flush.
==================
WARNING: ThreadSanitizer: unlock of an unlocked mutex (or by a wrong thread) (pid=17717)
    #0 pthread_mutex_unlock /opt/yb-build/llvm/yb-llvm-v7.1.0-1617644423-4856a933-build/src/llvm-project/compiler-rt/lib/tsan/../sanitizer_common/sanitizer_common_interceptors.inc:4085:3 (flush_job_test+0x470fbe)
    #1 rocksdb::port::Mutex::Unlock() /nfusr/centos-gcp-cloud/jenkins-worker-9tk17j/jenkins/jenkins-github-yugabyte-db-centos-master-clang7-tsan-913/build/tsan-clang7-dynamic-ninja/../../src/yb/rocksdb/port/port_posix.cc:86:25 (librocksdb.so+0x3bd876)
    #2 rocksdb::InstrumentedMutex::Unlock() /nfusr/centos-gcp-cloud/jenkins-worker-9tk17j/jenkins/jenkins-github-yugabyte-db-centos-master-clang7-tsan-913/build/tsan-clang7-dynamic-ninja/../../src/yb/rocksdb/util/instrumented_mutex.h:50:12 (flush_job_test+0x4c3009)
    #3 rocksdb::FlushJob::Run(rocksdb::FileMetaData*) /nfusr/centos-gcp-cloud/jenkins-worker-9tk17j/jenkins/jenkins-github-yugabyte-db-centos-master-clang7-tsan-913/build/tsan-clang7-dynamic-ninja/../../src/yb/rocksdb/db/flush_job.cc:164:18 (librocksdb.so+0x33cb5e)
    #4 rocksdb::FlushJobTest_Empty_Test::TestBody() /nfusr/centos-gcp-cloud/jenkins-worker-9tk17j/jenkins/jenkins-github-yugabyte-db-centos-master-clang7-tsan-913/build/tsan-clang7-dynamic-ninja/../../src/yb/rocksdb/db/flush_job_test.cc:117:3 (flush_job_test+0x4c021d)
    #5 void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20211222064218-dd4872fe56-centos7-x86_64-clang7/src/gmock-1.8.0/googletest/src/gtest.cc:2402:10 (libgmock.so+0x55d7f)
    #6 void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20211222064218-dd4872fe56-centos7-x86_64-clang7/src/gmock-1.8.0/googletest/src/gtest.cc:2438 (libgmock.so+0x55d7f)
    #7 testing::Test::Run() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20211222064218-dd4872fe56-centos7-x86_64-clang7/src/gmock-1.8.0/googletest/src/gtest.cc:2474:5 (libgmock.so+0x35128)
    #8 testing::TestInfo::Run() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20211222064218-dd4872fe56-centos7-x86_64-clang7/src/gmock-1.8.0/googletest/src/gtest.cc:2656:11 (libgmock.so+0x363bc)
    #9 testing::TestCase::Run() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20211222064218-dd4872fe56-centos7-x86_64-clang7/src/gmock-1.8.0/googletest/src/gtest.cc:2774:28 (libgmock.so+0x36e96)
    #10 testing::internal::UnitTestImpl::RunAllTests() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20211222064218-dd4872fe56-centos7-x86_64-clang7/src/gmock-1.8.0/googletest/src/gtest.cc:4649:43 (libgmock.so+0x431e6)
    #11 bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20211222064218-dd4872fe56-centos7-x86_64-clang7/src/gmock-1.8.0/googletest/src/gtest.cc:2402:10 (libgmock.so+0x56cef)
    #12 bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20211222064218-dd4872fe56-centos7-x86_64-clang7/src/gmock-1.8.0/googletest/src/gtest.cc:2438 (libgmock.so+0x56cef)
    #13 testing::UnitTest::Run() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20211222064218-dd4872fe56-centos7-x86_64-clang7/src/gmock-1.8.0/googletest/src/gtest.cc:4257:10 (libgmock.so+0x42a91)
    #14 RUN_ALL_TESTS() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20211222064218-dd4872fe56-centos7-x86_64-clang7/installed/tsan/include/gtest/gtest.h:2233:46 (flush_job_test+0x4c367b)
    #15 main /nfusr/centos-gcp-cloud/jenkins-worker-9tk17j/jenkins/jenkins-github-yugabyte-db-centos-master-clang7-tsan-913/build/tsan-clang7-dynamic-ninja/../../src/yb/rocksdb/db/flush_job_test.cc:243:10 (flush_job_test+0x4c1c26)

```

**Comment by rthallamko3** [comment]
Fixed in master.

**Comment by rthallamko3** [comment]
Ported to 2.12 branch too.

**Comment by def-** [comment]
This test is still failing in 2.8.9.0-b14. @rthallamko3 Do we want to backport this to 2.8?
```
==================
WARNING: ThreadSanitizer: unlock of an unlocked mutex (or by a wrong thread) (pid=25112)
    #0 pthread_mutex_unlock /opt/yb-build/llvm/yb-llvm-v7.1.0-1617644423-4856a933-build/src/llvm-project/compiler-rt/lib/tsan/../sanitizer_common/sanitizer_common_interceptors.inc:4085:3 (flush_job_test+0x471d3e)
    #1 rocksdb::port::Mutex::Unlock() /nfusr/centos-gcp-cloud/jenkins-worker-ybg6uy/jenkins/jenkins-github-yugabyte-db-centos-master-clang7-tsan-441/yugabyte-db/build/tsan-clang7-dynamic-ninja/../../src/yb/rocksdb/port/port_posix.cc:84:25 (librocksdb.so+0x3d8616)
    #2 rocksdb::InstrumentedMutex::Unlock() /nfusr/centos-gcp-cloud/jenkins-worker-ybg6uy/jenkins/jenkins-github-yugabyte-db-centos-master-clang7-tsan-441/yugabyte-db/build/tsan-clang7-dynamic-ninja/../../src/yb/rocksdb/util/instrumented_mutex.h:52:12 (flush_job_test+0x4c3da9)
    #3 rocksdb::FlushJob::Run(rocksdb::FileMetaData*) /nfusr/centos-gcp-cloud/jenkins-worker-ybg6uy/jenkins/jenkins-github-yugabyte-db-centos-master-clang7-tsan-441/yugabyte-db/build/tsan-clang7-dynamic-ninja/../../src/yb/rocksdb/db/flush_job.cc:162:18 (librocksdb.so+0x3573f1)
    #4 rocksdb::FlushJobTest_Empty_Test::TestBody() /nfusr/centos-gcp-cloud/jenkins-worker-ybg6uy/jenkins/jenkins-github-yugabyte-db-centos-master-clang7-tsan-441/yugabyte-db/build/tsan-clang7-dynamic-ninja/../../src/yb/rocksdb/db/flush_job_test.cc:116:3 (flush_job_test+0x4c0f9d)
    #5 void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20210916160346-44ba371965-centos7-x86_64-clang7/src/gmock-1.8.0/googletest/src/gtest.cc:2402:10 (libgmock.so+0x55d7f)
    #6 void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20210916160346-44ba371965-centos7-x86_64-clang7/src/gmock-1.8.0/googletest/src/gtest.cc:2438 (libgmock.so+0x55d7f)
    #7 testing::Test::Run() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20210916160346-44ba371965-centos7-x86_64-clang7/src/gmock-1.8.0/googletest/src/gtest.cc:2474:5 (libgmock.so+0x35128)
    #8 testing::TestInfo::Run() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20210916160346-44ba371965-centos7-x86_64-clang7/src/gmock-1.8.0/googletest/src/gtest.cc:2656:11 (libgmock.so+0x363bc)
    #9 testing::TestCase::Run() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20210916160346-44ba371965-centos7-x86_64-clang7/src/gmock-1.8.0/googletest/src/gtest.cc:2774:28 (libgmock.so+0x36e96)
    #10 testing::internal::UnitTestImpl::RunAllTests() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20210916160346-44ba371965-centos7-x86_64-clang7/src/gmock-1.8.0/googletest/src/gtest.cc:4649:43 (libgmock.so+0x431e6)
    #11 bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20210916160346-44ba371965-centos7-x86_64-clang7/src/gmock-1.8.0/googletest/src/gtest.cc:2402:10 (libgmock.so+0x56cef)
    #12 bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20210916160346-44ba371965-centos7-x86_64-clang7/src/gmock-1.8.0/googletest/src/gtest.cc:2438 (libgmock.so+0x56cef)
    #13 testing::UnitTest::Run() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20210916160346-44ba371965-centos7-x86_64-clang7/src/gmock-1.8.0/googletest/src/gtest.cc:4257:10 (libgmock.so+0x42a91)
    #14 RUN_ALL_TESTS() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20210916160346-44ba371965-centos7-x86_64-clang7/installed/tsan/include/gtest/gtest.h:2233:46 (flush_job_test+0x4c441b)
    #15 main /nfusr/centos-gcp-cloud/jenkins-worker-ybg6uy/jenkins/jenkins-github-yugabyte-db-centos-master-clang7-tsan-441/yugabyte-db/build/tsan-clang7-dynamic-ninja/../../src/yb/rocksdb/db/flush_job_test.cc:242:10 (flush_job_test+0x4c29d6)

  Location is heap block of size 1416 at 0x7b6800000000 allocated by main thread:
    #0 operator new(unsigned long) /opt/yb-build/llvm/yb-llvm-v7.1.0-1617644423-4856a933-build/src/llvm-project/compiler-rt/lib/tsan/rtl/tsan_new_delete.cc:65:3 (flush_job_test+0x4c007d)
    #1 testing::internal::TestFactoryImpl<rocksdb::FlushJobTest_Empty_Test>::CreateTest() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20210916160346-44ba371965-centos7-x86_64-clang7/installed/tsan/include/gtest/internal/gtest-internal.h:484:39 (flush_job_test+0x4c46a9)
    #2 testing::Test* testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::TestFactoryBase, testing::Test*>(testing::internal::TestFactoryBase*, testing::Test* (testing::internal::TestFactoryBase::*)(), char const*) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20210916160346-44ba371965-centos7-x86_64-clang7/src/gmock-1.8.0/googletest/src/gtest.cc:2402:10 (libgmock.so+0x5627f)
    #3 testing::Test* testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::TestFactoryBase, testing::Test*>(testing::internal::TestFactoryBase*, testing::Test* (testing::internal::TestFactoryBase::*)(), char const*) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20210916160346-44ba371965-centos7-x86_64-clang7/src/gmock-1.8.0/googletest/src/gtest.cc:2438 (libgmock.so+0x5627f)
    #4 testing::TestInfo::Run() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20210916160346-44ba371965-centos7-x86_64-clang7/src/gmock-1.8.0/googletest/src/gtest.cc:2647:22 (libgmock.so+0x3631b)
    #5 testing::TestCase::Run() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20210916160346-44ba371965-centos7-x86_64-clang7/src/gmock-1.8.0/googletest/src/gtest.cc:2774:28 (libgmock.so+0x36e96)
    #6 testing::internal::UnitTestImpl::RunAllTests() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20210916160346-44ba371965-centos7-x86_64-clang7/src/gmock-1.8.0/googletest/src/gtest.cc:4649:43 (libgmock.so+0x431e6)
    #7 bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20210916160346-44ba371965-centos7-x86_64-clang7/src/gmock-1.8.0/googletest/src/gtest.cc:2402:10 (libgmock.so+0x56cef)
    #8 bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20210916160346-44ba371965-centos7-x86_64-clang7/src/gmock-1.8.0/googletest/src/gtest.cc:2438 (libgmock.so+0x56cef)
    #9 testing::UnitTest::Run() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20210916160346-44ba371965-centos7-x86_64-clang7/src/gmock-1.8.0/googletest/src/gtest.cc:4257:10 (libgmock.so+0x42a91)
    #10 RUN_ALL_TESTS() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20210916160346-44ba371965-centos7-x86_64-clang7/installed/tsan/include/gtest/gtest.h:2233:46 (flush_job_test+0x4c441b)
    #11 main /nfusr/centos-gcp-cloud/jenkins-worker-ybg6uy/jenkins/jenkins-github-yugabyte-db-centos-master-clang7-tsan-441/yugabyte-db/build/tsan-clang7-dynamic-ninja/../../src/yb/rocksdb/db/flush_job_test.cc:242:10 (flush_job_test+0x4c29d6)

  Mutex M66785 (0x7b6800000528) created at:
    #0 pthread_mutex_init /opt/yb-build/llvm/yb-llvm-v7.1.0-1617644423-4856a933-build/src/llvm-project/compiler-rt/lib/tsan/rtl/tsan_interceptors.cc:1184:3 (flush_job_test+0x457183)
    #1 rocksdb::port::Mutex::Mutex(bool) /nfusr/centos-gcp-cloud/jenkins-worker-ybg6uy/jenkins/jenkins-github-yugabyte-db-centos-master-clang7-tsan-441/yugabyte-db/build/tsan-clang7-dynamic-ninja/../../src/yb/rocksdb/port/port_posix.cc:55:31 (librocksdb.so+0x3d84c4)
    #2 rocksdb::InstrumentedMutex::InstrumentedMutex(bool) /nfusr/centos-gcp-cloud/jenkins-worker-ybg6uy/jenkins/jenkins-github-yugabyte-db-centos-master-clang7-tsan-441/yugabyte-db/build/tsan-clang7-dynamic-ninja/../../src/yb/rocksdb/util/instrumented_mutex.h:40:9 (flush_job_test+0x4c5150)
    #3 rocksdb::FlushJobTest::FlushJobTest() /nfusr/centos-gcp-cloud/jenkins-worker-ybg6uy/jenkins/jenkins-github-yugabyte-db-centos-master-clang7-tsan-441/yugabyte-db/build/tsan-clang7-dynamic-ninja/../../src/yb/rocksdb/db/flush_job_test.cc:46:3 (flush_job_test+0x4c4911)
    #4 rocksdb::FlushJobTest_Empty_Test::FlushJobTest_Empty_Test() /nfusr/centos-gcp-cloud/jenkins-worker-ybg6uy/jenkins/jenkins-github-yugabyte-db-centos-master-clang7-tsan-441/yugabyte-db/build/tsan-clang7-dynamic-ninja/../../src/yb/rocksdb/db/flush_job_test.cc:106:1 (flush_job_test+0x4c470a)
    #5 testing::internal::TestFactoryImpl<rocksdb::FlushJobTest_Empty_Test>::CreateTest() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20210916160346-44ba371965-centos7-x86_64-clang7/installed/tsan/include/gtest/internal/gtest-internal.h:484:43 (flush_job_test+0x4c46b4)
    #6 testing::Test* testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::TestFactoryBase, testing::Test*>(testing::internal::TestFactoryBase*, testing::Test* (testing::internal::TestFactoryBase::*)(), char const*) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20210916160346-44ba371965-centos7-x86_64-clang7/src/gmock-1.8.0/googletest/src/gtest.cc:2402:10 (libgmock.so+0x5627f)
    #7 testing::Test* testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::TestFactoryBase, testing::Test*>(testing::internal::TestFactoryBase*, testing::Test* (testing::internal::TestFactoryBase::*)(), char const*) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20210916160346-44ba371965-centos7-x86_64-clang7/src/gmock-1.8.0/googletest/src/gtest.cc:2438 (libgmock.so+0x5627f)
    #8 testing::TestInfo::Run() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20210916160346-44ba371965-centos7-x86_64-clang7/src/gmock-1.8.0/googletest/src/gtest.cc:2647:22 (libgmock.so+0x3631b)
    #9 testing::TestCase::Run() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20210916160346-44ba371965-centos7-x86_64-clang7/src/gmock-1.8.0/googletest/src/gtest.cc:2774:28 (libgmock.so+0x36e96)
    #10 testing::internal::UnitTestImpl::RunAllTests() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20210916160346-44ba371965-centos7-x86_64-clang7/src/gmock-1.8.0/googletest/src/gtest.cc:4649:43 (libgmock.so+0x431e6)
    #11 bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20210916160346-44ba371965-centos7-x86_64-clang7/src/gmock-1.8.0/googletest/src/gtest.cc:2402:10 (libgmock.so+0x56cef)
    #12 bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20210916160346-44ba371965-centos7-x86_64-clang7/src/gmock-1.8.0/googletest/src/gtest.cc:2438 (libgmock.so+0x56cef)
    #13 testing::UnitTest::Run() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20210916160346-44ba371965-centos7-x86_64-clang7/src/gmock-1.8.0/googletest/src/gtest.cc:4257:10 (libgmock.so+0x42a91)
    #14 RUN_ALL_TESTS() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20210916160346-44ba371965-centos7-x86_64-clang7/installed/tsan/include/gtest/gtest.h:2233:46 (flush_job_test+0x4c441b)
    #15 main /nfusr/centos-gcp-cloud/jenkins-worker-ybg6uy/jenkins/jenkins-github-yugabyte-db-centos-master-clang7-tsan-441/yugabyte-db/build/tsan-clang7-dynamic-ninja/../../src/yb/rocksdb/db/flush_job_test.cc:242:10 (flush_job_test+0x4c29d6)

SUMMARY: ThreadSanitizer: unlock of an unlocked mutex (or by a wrong thread) /nfusr/centos-gcp-cloud/jenkins-worker-ybg6uy/jenkins/jenkins-github-yugabyte-db-centos-master-clang7-tsan-441/yugabyte-db/build/tsan-clang7-dynamic-ninja/../../src/yb/rocksdb/port/port_posix.cc:84:25 in rocksdb::port::Mutex::Unlock()
==================
```
