### ISSUE TITLE
[YSQL] tserver failed starting PG during server restart

### ISSUE THREAD

**Issue by SteveXiSong** [yugabyte/yugabyte-db#12871]
Jira Link: [DB-2626](https://yugabyte.atlassian.net/browse/DB-2626)
### Description

The tserver failed to start PG with logs:
```
...
Failed when waiting for PostgreSQL server to exit: Illegal state (yb/util/subprocess.cc:444): DoWait called on a process that is not running, waiting a bit
<repeat>
...
```

~~This issue might be related to https://github.com/yugabyte/yugabyte-db/issues/12784.~~ The log in this issue is from server. We should locate the actual in PG to tell us more details.

Ref:
discussion thread: https://yugabyte.slack.com/archives/CAR5BCH29/p1655144419422059

**Comment by SteveXiSong** [comment]
Before all failed restart, I found this err msg from tserver:
```
Failed trying to start PostgreSQL server: Runtime error (yb/util/subprocess.cc:325): Unable to fork: Cannot allocate memory (system error 12), waiting a bit
```
from
```
account-id:aea83bbd-8b66-4a4f-ba11-af7dc9a47147,c-t4lzkraq2vabhfu3gmkxc5av4m,cluster-id:9f179544-10d5-4013-969b-3315717415e3,cluster-tier:paid,datadog.index:main,env:dev,filename:yb-tserver.info,instance-id:2454926429644744670,instance-type:n2-standard-2,internal-hostname:yb-cloud-c-t4lzkraq2vabhfu3gmkxc5av4m-n2.c.yugabyte-cloud-dev.internal,node-uuid:deb77869-2b5e-48d8-96ef-bb08ad2c281f,numeric_project_id:105931836404,primary-user-email:pytest,project-id:aca28192-6e89-4026-8a53-634fc47ebfd3,project:yugabyte-cloud-dev,server_type:cluster-server,service:yb-tserver,source:yugabyte,sourcecategory:database,universe-uuid:9f179544-10d5-4013-969b-3315717415e3,yugaware-server,zone:us-central1-c
```

**Comment by SteveXiSong** [comment]
The host stuck at restarting PG for a long time (>5min) before we saw illegal state.

https://app.datadoghq.com/logs?query=cluster-id%3A9f179544-10d5-4013-969b-3315717415e3%20-service%3A%28yb-master%20OR%20journald%29&agg_q=status%2Cservice&cols=service&index=&sort_m=%2C&sort_t=%2C&stream_sort=time%2Casc&top_n=10%2C10&top_o=top%2Ctop&viz=stream&from_ts=1653983700000&to_ts=1653984300000&live=false

**Comment by SteveXiSong** [comment]
The very first PG restart happened 
{
	"id": "AQAAAYEZF287Gte1yQAAAABBWUVaRjRMTEFBQWFmbDdKM2RONHp3QVg",
	"content": {
		"timestamp": "2022-05-31T07:49:35.163Z",
		"tags": [
			"filename:yb-tserver.info",
			"sourcecategory:database",
			"source:yugabyte",
			"service:yb-tserver",
			"account-id:aea83bbd-8b66-4a4f-ba11-af7dc9a47147",
			"c-t4lzkraq2vabhfu3gmkxc5av4m",
			"cluster-id:9f179544-10d5-4013-969b-3315717415e3",
			"cluster-tier:paid",
			"env:dev",
			"instance-id:2454926429644744670",
			"instance-type:n2-standard-2",
			"internal-hostname:yb-cloud-c-t4lzkraq2vabhfu3gmkxc5av4m-n2.c.yugabyte-cloud-dev.internal",
			"node-uuid:deb77869-2b5e-48d8-96ef-bb08ad2c281f",
			"numeric_project_id:105931836404",
			"primary-user-email:pytest",
			"project-id:aca28192-6e89-4026-8a53-634fc47ebfd3",
			"project:yugabyte-cloud-dev",
			"server_type:cluster-server",
			"universe-uuid:9f179544-10d5-4013-969b-3315717415e3",
			"yugaware-server",
			"zone:us-central1-c"
		],
		"host": "yb-cloud-c-t4lzkraq2vabhfu3gmkxc5av4m-n2.c.yugabyte-cloud-dev.internal",
		"service": "yb-tserver",
		"message": "Restarting PostgreSQL server",
		"attributes": {
			"logger": {
				"line": 722,
				"name": "pg_wrapper.cc",
				"thread_id": 32590
			},
			"timestamp": 1653983375163,
			"level": "I"
		}
	}
}
Before this, I observed that tserver got restarted.

**Comment by SteveXiSong** [comment]
Also found

```


May 31 00:49:33.640 | yb-tserver | Data directory /mnt/d0/pg_data already exists, skipping initdb
-- | -- | --
  | May 31 00:49:33.640 | yb-tserver | Starting PostgreSQL server listening on 0.0.0.0, port 5433
  | May 31 00:49:33.641 | yb-tserver | Killing older postgres process: 1595
  | May 31 00:49:33.641 | yb-tserver | Starting PostgreSQL server
  | May 31 00:49:33.659 | yb-tserver | PostgreSQL server running as pid 32589


```

**Comment by SteveXiSong** [comment]
On prod cluster
```
{
	"id": "AQAAAYFcfWO9KsR4KQAAAABBWUZjZlhSSEFBRDY0ZjBSRHBNOU1nQUM",
	"content": {
		"timestamp": "2022-06-13T09:55:30.365Z",
		"tags": [
			"filename:yb-tserver.info",
			"sourcecategory:database",
			"source:yugabyte",
			"service:yb-tserver",
			"account-id:1f042566-9768-4e50-b124-ca3d16510862",
			"cluster-id:e0dd2601-6008-4674-90b7-792e0ab09f08",
			"cluster-tier:paid",
			"customer-uuid:0f487263-17b1-48e4-b9e4-7715fc5c3521",
			"env:prod",
			"launched-by:unknown",
			"name:yb-cloud-c-4dosmalabbdhjefxpexavme7ba-n5",
			"node-uuid:90129f53-9e54-3afc-8f70-99ef864437ec",
			"project-id:d71be85b-802d-44fc-bd96-635174cad401",
			"universe-uuid:e0dd2601-6008-4674-90b7-792e0ab09f08",
			"yb-server-type:cluster-server"
		],
		"host": "i-0da954d7adce68b78",
		"service": "yb-tserver",
		"message": "Failed trying to start PostgreSQL server: IO error (yb/util/subprocess.cc:410): Tried to close file descriptors as part of posix_spawn: [22, 29, 30, 31, 32, 33, 34, 39, 67, 69, 75, 76, 77, 78, 81, 82, 108, 109, 110, 111, 113, 116, 119, 120, 122, 123, 124, 125, 127, 129, 130, 135, 136, 138, 139, 141, 143, 144, 145, 146, 148, 150, 151, 152, 153, 155, 156, 157, 159, 160, 161, 165, 166, 168, 169, 171, 172, 174, 175, 176, 177, 178, 181, 182, 183, 186, 187, 190, 191, 194, 195, 196, 198, 199, 200, 201, 203, 204, 205, 206, 207, 209, 210, 214, 215, 217, 219, 220, 222, 223, 224, 225, 226, 227, 228, 234, 235, 236, 237, 239, 240, 241, 242, 243, 244, 246, 247, 248, 249, 250, 251, 252, 253, 254, 256, 260, 261, 262, 263, 266, 267, 268, 270, 271, 272, 273, 274, 275, 277, 278, 279, 285, 289, 291, 297, 305, 306, 307, 308, 310, 311, 313, 314, 316, 320, 321, 322, 325, 326, 327, 328, 329, 331, 343, 354, 358, 360, 361, 363, 364, 365, 366, 371, 379, 385, 386, 396, 400, 401, 405, 410, 411, 412, 414, 417, 418, 421, 423, 424, 425, 426, 431, 438, 439, 440, 444, 448, 449, 457, 462, 466, 467, 476, 477, 480, 481, 485, 486, 487, 490, 494, 495, 496, 497, 499, 500, 501, 502, 506, 510, 511, 512, 514, 515, 516, 519, 520, 521, 522, 523, 524, 525, 535, 541, 543, 544, 545, 547, 548, 549, 550, 551, 552, 553, 561, 565, 567, 569, 572, 574, 576, 577, 578, 580, 581, 582, 583, 584, 585, 596, 597, 598, 602, 606, 607, 608, 613, 618, 619, 621, 622, 623, 624, 625, 626, 630, 633, 638, 642, 644, 645, 647, 648, 649, 650, 651, 652, 653, 655, 656, 659, 660, 662, 663, 664, 665, 666, 668, 674, 675, 688, 689, 690, 691, 694, 695, 696, 697, 698, 699, 700, 704, 708, 714, 717, 720, 722, 723, 725, 726, 727, 728, 732, 740, 742, 749, 751, 752, 753, 756, 757, 758, 759, 762, 763, 770, 775, 776, 777, 779, 780, 784, 785, 786, 787, 789, 790, 798, 799, 800, 801, 803, 805, 811, 812, 814, 816, 819, 821, 822, 832, 835, 836, 842, 846, 847, 848, 853, 854, 856, 857, 859, 861, 862, 863, 869, 875, 876, 878, 879, 880, 881, 885, 889, 894, 895, 896, 899, 901, 902, 903, 904, 905, 906, 908, 909, 910, 913, 915, 922, 923, 924, 928, 932, 937, 938, 942, 948, 949, 953, 955, 956, 957, 959, 960, 961, 962, 963, 964, 968, 977, 978, 979, 980, 984, 992, 993, 996, 997, 1004, 1006, 1007, 1008, 1018, 1020, 1024, 1027, 1031, 1034, 1044, 1051, 1052, 1054, 1060, 1061, 1063, 1065, 1069, 1070, 1072, 1073, 1074, 1075, 1079, 1084, 1085, 1086, 1091, 1092, 1094, 1095, 1096, 1098, 1099, 1103, 1104, 1106, 1107, 1111, 1115, 1119, 1120, 1121, 1123, 1124, 1125, 1126, 1127, 1128, 1129, 1130, 1132, 1133, 1136, 1144, 1150, 1151, 1162, 1163, 1168, 1175, 1176, 1178, 1179, 1180, 1186, 1194, 1195, 1198, 1202, 1204, 1206, 1211, 1214, 1217, 1220, 1222, 1228, 1229, 1235, 1242, 1243, 1244, 1245, 1249, 1260, 1261, 1263, 1264, 1265, 1266, 1268, 1269, 1270, 1272, 1273, 1274, 1275, 1279, 1284, 1285, 1286, 1288, 1289, 1290, 1291, 1295, 1299, 1300, 1303, 1304, 1305, 1306, 1307, 1311, 1324, 1325, 1326, 1327, 1331, 1337, 1339, 1341, 1347, 1348, 1350, 1351, 1352, 1353, 1357, 1365, 1368, 1370, 1372, 1381, 1382, 1384, 1386, 1388, 1389, 1390, 1392, 1393, 1394, 1395, 1399, 1406, 1407, 1408, 1409, 1412, 1413, 1414, 1415, 1416, 1418, 1419, 1420, 1421, 1425, 1431, 1433, 1434, 1435, 1436, 1440, 1441, 1446, 1447, 1452, 1456, 1466, 1467, 1468, 1470, 1471, 1472, 1473, 1475, 1478, 1479, 1480, 1482, 1486, 1491, 1492, 1497, 1505, 1506, 1507, 1508, 1509, 1510, 1513, 1516, 1522, 1523, 1524, 1525, 1526, 1528, 1531, 1532, 1533, 1534, 1537, 1539, 1546, 1547, 1548, 1549, 1550, 1551, 1552, 1553, 1554, 1558, 1568, 1569, 1573, 1577, 1582, 1583, 1584, 1585, 1586, 1589, 1590, 1592, 1593, 1594, 1598, 1599, 1600, 1601, 1603, 1604, 1605, 1606, 1607, 1608, 1609, 1611, 1613, 1616, 1622, 1624, 1625, 1629, 1632, 1633, 1637, 1638, 1640, 1641, 1645, 1646, 1647, 1651, 1652, 1653, 1654, 1655, 1658, 1660, 1663, 1664, 1665, 1666, 1670, 1674, 1676, 1682, 1683, 1684, 1689, 1699, 1700, 1701, 1702, 1703, 1705, 1706, 1708, 1709, 1710, 1711, 1712, 1713, 1714, 1715, 1719, 1722, 1723, 1724, 1725, 1726, 1727, 1737, 1738, 1740, 1741, 1745, 1749, 1754, 1756, 1758, 1762, 1763, 1764, 1765, 1766, 1767, 1770, 1771, 1773, 1774, 1776, 1782, 1790, 1791, 1792, 1796, 1797, 1800, 1801, 1802, 1806, 1808, 1809, 1810, 1812, 1813, 1817, 1821, 1824, 1825, 1826, 1827, 1831, 1837, 1838, 1840, 1841, 1842, 1843, 1847, 1859, 1867, 1872, 1876, 1882, 1883, 1884, 1886, 1887, 1888, 1889, 1890, 1891, 1892, 1899, 1901, 1915, 1917, 1918, 1920, 1921, 1922, 1923, 1924, 1928, 1932, 1933, 1947, 1948, 1952, 1954, 1956, 1961, 1968, 1971, 1974, 1976, 1977, 1978, 1979, 1982, 1984, 1988, 1989, 1990, 1991, 1992, 1995, 1997, 2002, 2004, 2005, 2012, 2019, 2020, 2021, 2023, 2024, 2025, 2026, 2030, 2042, 2043, 2044, 2045, 2048, 2050, 2051, 2052, 2054, 2057, 2058, 2059, 2061, 2063, 2071, 2081, 2088, 2089, 2090, 2091, 2092, 2093, 2097, 2102, 2112, 2116, 2117, 2120, 2121, 2122, 2123, 2124, 2125, 2130, 2136, 2137, 2138, 2140, 2141, 2142, 2143, 2144, 2145, 2146, 2148, 2152, 2153, 2157, 2161, 2169, 2170, 2171, 2173, 2178, 2184, 2188, 2199, 2206, 2207, 2208, 2209, 2217, 2218, 2220, 2224, 2237, 2238, 2239, 2240, 2243, 2244, 2245, 2246, 2247, 2248, 2249, 2250, 2257, 2271, 2274, 2275, 2278, 2279, 2281, 2282, 2283, 2286, 2287, 2288, 2289, 2293, 2308, 2313, 2314, 2315, 2319, 2323, 2326, 2342, 2343, 2344, 2352, 2360, 2361, 2363, 2364, 2365, 2366, 2367, 2368, 2369, 2376, 2382, 2383, 2385, 2390, 2399, 2403, 2404, 2406, 2412, 2414, 2415, 2417, 2418, 2420, 2421, 2422, 2423, 2424, 2425, 2426, 2430, 2434, 2435, 2438, 2443, 2455, 2457, 2458, 2460, 2462, 2463, 2464, 2465, 2466, 2467, 2472, 2481, 2488, 2490, 2491, 2492, 2495, 2496, 2498, 2499, 2500, 2501, 2507, 2514, 2515, 2516, 2517, 2519, 2520, 2526, 2527, 2528, 2529, 2530, 2532, 2533, 2536, 2541, 2544, 2565, 2566, 2572, 2573, 2574, 2576, 2577, 2578, 2579, 2581, 2582, 2586, 2589, 2597, 2598, 2600, 2603, 2604, 2606, 2609, 2610, 2612, 2621, 2622, 2624, 2625, 2626, 2627, 2628, 2629, 2632, 2637, 2644, 2650, 2655, 2656, 2660, 2662, 2663, 2664, 2666, 2667, 2668, 2669, 2670, 2671, 2672, 2674, 2676, 2680, 2682, 2685, 2688, 2691, 2692, 2693, 2694, 2699, 2700, 2702, 2703, 2705, 2706, 2710, 2711, 2713, 2714, 2715, 2717, 2718, 2719, 2720, 2722, 2725, 2729, 2730, 2731, 2733, 2739, 2742, 2744, 2749, 2750, 2752, 2756, 2760, 2761, 2764, 2767, 2768, 2769, 2770, 2772, 2773, 2774, 2775, 2776, 2782, 2788, 2789, 2791, 2792, 2793, 2794, 2795, 2796, 2797, 2798, 2799, 2802, 2804, 2808, 2812, 2813, 2814, 2815, 2817, 2818, 2819, 2820, 2825, 2829, 2830, 2831, 2832, 2833, 2834, 2847, 2849, 2857, 2860, 2862, 2866, 2871, 2872, 2873, 2875, 2876, 2877, 2878, 2883, 2893, 2894, 2902, 2903, 2908, 2909, 2912, 2921, 2922, 2923, 2924, 2925, 2926, 2928, 2931, 2932, 2934, 2936, 2940, 2941, 2942, 2943, 2945, 2947, 2949, 2950, 2951, 2952, 2953, 2957, 2961, 2967, 2968, 2969, 2970, 2974, 2978, 2979, 2980, 2981, 2983, 2984, 2985, 2986, 2987, 2988, 2992, 2998, 2999, 3000, 3001, 3004, 3005, 3006, 3007, 3009, 3010, 3011, 3013, 3015, 3017, 3021, 3026, 3027, 3028, 3032, 3036, 3037, 3038, 3039, 3040, 3042, 3043, 3044, 3045, 3047, 3051, 3052, 3064, 3066, 3068, 3073, 3076, 3079, 3080, 3081, 3082, 3083, 3084, 3086, 3087, 3088, 3097, 3101, 3102, 3106, 3107, 3108, 3109, 3110, 3114, 3115, 3116, 3117, 3118, 3120, 3122, 3126, 3130, 3132, 3134, 3135, 3138, 3141, 3142, 3146, 3147, 3148, 3149, 3151, 3157, 3158, 3159, 3160, 3164, 3165, 3166, 3168, 3169, 3177, 3181, 3182, 3183, 3185, 3189, 3191, 3193, 3196, 3197, 3198, 3199, 3200, 3201, 3205, 3209, 3211, 3212, 3214, 3215, 3216, 3217, 3221, 3231, 3232, 3236, 3238, 3239, 3241, 3242, 3244, 3245, 3246, 3247, 3251, 3256, 3257, 3258, 3260, 3261, 3262, 3263, 3267, 3278, 3279, 3280, 3281, 3282, 3289, 3291, 3292, 3295, 3298, 3300, 3304, 3305, 3309, 3319, 3321, 3322, 3324, 3325, 3326, 3327, 3331, 3336, 3337, 3341, 3342, 3348, 3351, 3352, 3354, 3355, 3356, 3357, 3361, 3372, 3379, 3380, 3382, 3383, 3384, 3385, 3389, 3395, 3396, 3398, 3399, 3400, 3401, 3405, 3424, 3425, 3427, 3431, 3436, 3437, 3438, 3439, 3440, 3441, 3444, 3445, 3449, 3458, 3462, 3468, 3469, 3471, 3472, 3473, 3474, 3478, 3484, 3485, 3487, 3488, 3489, 3490, 3494, 3524, 3528, 3534, 3535, 3537, 3542, 3547, 3548, 3552, 3556, 3558, 3559, 3561, 3562, 3563, 3564, 3568, 3574, 3575, 3578, 3579, 3580, 3581, 3585, 3595, 3596, 3598, 3599, 3600, 3601, 3605, 3626, 3630, 3640, 3641, 3644, 3645, 3647, 3648, 3649, 3650, 3654, 3662, 3663, 3664, 3665, 3666, 3669, 3670, 3671, 3675, 3679, 3687, 3688, 3690, 3691, 3692, 3693, 3697, 3705, 3713, 3717, 3718, 3720, 3721, 3722, 3723, 3727, 3734, 3740, 3750, 3755, 3759, 3765, 3766, 3768, 3769, 3770, 3772, 3776, 3780, 3781, 3782, 3783, 3784, 3785, 3786, 3788, 3789, 3790, 3791, 3792, 3795, 3797, 3799, 3811, 3814, 3819, 3823, 3827, 3829, 3831, 3841, 3843, 3844, 3846, 3847, 3848, 3849, 3854, 3855, 3863, 3890, 3893, 3895, 3906, 3918, 3919, 3927, 3932, 3933, 3934, 3935, 3936, 3945, 3946, 3948, 3952, 3953, 3956, 3971, 3974, 3975, 3976, 3980, 3984, 3985, 4002, 4004, 4015, 4023, 4025, 4026, 4029, 4041, 4042, 4043, 4044, 4045, 4046, 4048, 4049, 4052, 4058, 4059, 4060, 4061, 4065, 4073, 4075, 4083, 4088, 4095, 4096, 4098, 4099, 4100, 4101, 4105, 4132, 4133, 4152, 4157, 4175, 4180, 4181, 4183, 4192, 4193, 4194, 4198, 4204, 4205, 4208, 4211, 4216, 4223, 4224, 4228, 4234, 4235, 4237, 4238, 4239, 4240, 4246, 4256, 4257, 4262, 4263, 4265, 4266, 4267, 4268, 4272, 4297, 4300, 4301, 4302, 4304, 4310, 4314, 4326, 4327, 4329, 4344, 4345, 4349, 4357, 4358, 4360, 4361, 4362, 4363, 4367, 4373, 4374, 4376, 4377, 4378, 4379, 4383, 4405, 4406, 4407, 4409, 4410, 4411, 4415, 4428, 4429, 4431, 4433, 4435, 4436, 4437, 4444, 4448, 4474, 4475, 4480, 4481, 4490, 4491, 4496, 4498, 4513, 4526, 4527, 4529, 4538, 4539, 4540, 4544, 4551, 4552, 4554, 4555, 4556, 4557, 4561, 4567, 4568, 4570, 4571, 4572, 4573, 4577, 4597, 4598, 4601, 4605, 4612, 4613, 4615, 4618, 4619, 4620, 4622, 4627, 4629, 4631, 4647, 4650, 4651, 4653, 4654, 4655, 4656, 4657, 4662, 4671, 4677, 4678, 4689, 4693, 4694, 4696, 4697, 4698, 4699, 4701, 4705, 4706, 4709, 4721, 4723, 4724, 4727, 4730, 4734, 4737, 4738, 4739, 4740, 4742, 4743, 4744, 4745, 4749, 4757, 4758, 4762, 4766, 4767, 4775, 4778, 4783, 4784, 4786, 4790, 4791, 4794, 4796, 4805, 4806, 4808, 4812, 4813, 4816, 4818, 4821, 4822, 4824, 4828, 4829, 4832, 4834, 4837, 4838, 4839, 4840, 4842, 4843, 4845, 4849, 4853, 4855, 4858, 4862, 4866, 4867, 4869, 4870, 4871, 4872, 4874, 4875, 4877, 4881, 4888, 4889, 4891, 4892, 4896, 4900, 4903, 4904, 4905, 4906, 4908, 4909, 4910, 4911, 4928, 4939, 4940, 4941, 4942, 4947, 4948, 4950, 4951, 4953, 4957, 4958, 4959, 4962, 4964, 4965, 4969, 4970, 4974, 4975, 4979, 4980, 4984, 4988, 4993, 4994, 4999, 5003, 5006, 5007, 5009, 5010, 5014, 5015, 5016, 5021, 5022, 5025, 5026, 5028, 5033, 5037, 5039, 5040, 5042, 5043, 5045, 5047, 5048, 5052, 5054, 5055, 5057, 5059, 5062, 5063, 5068, 5083, 5087, 5091, 5097, 5099, 5104, 5111, 5112, 5114, 5115, 5116, 5118, 5119, 5120, 5124, 5130, 5131, 5132, 5135, 5145, 5149, 5150, 5151, 5154, 5155, 5157, 5159, 5161, 5165, 5170, 5174, 5175, 5177, 5178, 5182, 5185, 5186, 5188, 5189, 5190, 5191, 5192, 5193, 5200, 5204, 5208, 5209, 5214, 5216, 5217, 5218, 5220, 5221, 5222, 5223, 5227, 5229, 5233, 5236, 5238, 5242, 5245, 5246, 5247, 5248, 5251, 5252, 5254, 5258, 5261, 5263, 5264, 5267, 5268, 5271, 5273, 5274, 5277, 5282, 5283, 5284, 5290, 5293, 5294, 5297, 5298, 5299, 5300, 5305, 5306, 5307, 5308, 5309, 5315, 5316, 5322, 5327, 5328, 5329, 5330, 5332, 5333, 5334, 5335, 5336, 5337, 5338, 5343, 5348, 5352, 5354, 5355, 5356, 5362, 5364, 5365, 5366, 5367, 5368, 5369, 5370, 5375, 5385, 5389, 5390, 5393, 5394, 5400, 5401, 5403, 5404, 5405, 5407, 5408, 5409, 5412, 5416, 5420, 5426, 5427, 5428, 5434, 5435, 5437, 5438, 5439, 5440, 5441, 5442, 5446, 5450, 5454, 5460, 5461, 5463, 5466, 5467, 5469, 5470, 5471, 5472, 5473, 5474, 5475, 5482, 5483, 5494, 5495, 5497, 5498, 5499, 5501, 5504, 5516, 5517, 5519, 5520, 5521, 5523, 5532, 5539, 5545, 5546, 5553, 5556, 5557, 5558, 5569, 5573, 5605, 5609, 5615, 5616, 5618, 5619, 5620, 5621, 5625, 5631, 5632, 5634, 5635, 5636, 5637, 5641, 5647, 5648, 5650, 5651, 5652, 5654, 5658, 5672, 5676, 5682, 5683, 5689, 5694, 5695, 5696, 5700, 5706, 5707, 5709, 5710, 5711, 5715, 5721, 5722, 5724, 5725, 5726, 5727, 5731, 5735, 5737, 5738, 5740, 5742, 5743, 5744, 5747, 5755, 5765, 5778, 5779, 5781, 5784, 5785, 5789, 5791, 5799, 5800, 5808, 5817, 5818, 5819, 5826, 5835, 5836, 5838, 5839, 5840, 5841, 5842, 5845, 5849, 5852, 5859, 5860, 5861, 5865, 5876, 5885, 5886, 5887, 5888, 5889, 5890, 5898, 5902, 5903, 5908, 5916, 5917, 5919, 5922, 5923, 5925, 5927, 5931, 5932, 5936, 5937, 5939, 5940, 5947, 5954, 5965, 5971, 5972, 5974, 5991, 5992, 5995, 6001, 6003, 6012, 6013, 6014, 6019, 6030, 6031, 6032, 6045, 6066, 6071, 6077, 6085, 6086, 6088, 6092, 6093, 6098, 6099, 6108, 6134, 6135, 6137, 6138, 6142, 6146, 6155, 6157, 6171, 6181, 6186, 6189, 6190, 6194, 6195, 6196, 6203, 6204, 6221, 6224, 6225, 6226, 6228, 6230, 6234, 6241, 6243, 6245, 6248, 6250, 6254, 6260, 6261, 6270, 6271, 6275, 6277, 6281, 6284, 6285, 6287, 6288, 6289, 6290, 6291, 6296, 6304, 6311, 6312, 6315, 6321, 6333, 6340, 6341, 6342, 6343, 6345, 6346, 6350, 6351, 6352, 6358, 6359, 6361, 6365, 6369, 6370, 6372, 6393, 6394, 6395, 6402, 6403, 6406, 6407, 6408, 6409, 6410, 6411, 6413, 6414, 6417, 6442, 6443, 6444, 6451, 6452, 6454, 6455, 6456, 6457, 6458, 6459, 6460, 6464, 6468, 6472, 6494, 6496, 6497, 6498, 6499, 6502, 6503, 6504, 6505, 6506, 6508, 6509, 6512, 6516, 6521, 6522, 6524, 6525, 6527, 6532, 6533, 6535, 6536, 6537, 6538, 6539, 6540, 6541, 6548, 6554, 6556, 6559, 6568, 6569, 6571, 6572, 6573, 6574, 6575, 6576, 6578, 6584, 6588, 6594, 6596, 6599, 6600, 6601, 6603, 6604, 6605, 6606, 6607, 6608, 6609, 6616, 6620, 6624, 6635, 6636, 6637, 6638, 6640, 6642, 6643, 6644, 6646, 6647, 6650, 6653, 6666, 6672, 6673, 6675, 6680, 6681, 6682, 6692, 6693, 6695, 6696, 6697, 6698, 6702, 6738, 6742, 6771, 6775, 6783, 6784, 6786, 6787, 6788, 6789, 6793, 6821, 6826, 6830, 6834, 6879, 6885, 6906, 6913, 6914, 6916, 6917, 6918, 6919, 6923, 6934, 6935, 6936, 6938, 6940, 6942, 6949, 6955, 6965, 6969, 6973, 6982, 6983, 6990, 7003, 7004, 7005, 7011, 7035, 7040, 7046, 7047, 7049, 7050, 7051, 7052, 7056, 7062, 7063, 7065, 7066, 7067, 7068, 7071, 7080, 7091, 7097, 7098, 7102, 7103, 7110, 7111, 7115, 7151, 7155, 7161, 7162, 7164, 7165, 7166, 7167, 7172, 7179, 7180, 7182, 7184, 7187, 7188, 7189, 7191, 7199, 7200, 7202, 7206, 7210, 7213, 7214, 7216, 7217, 7218, 7219, 7220, 7221, 7229, 7233, 7234, 7238, 7242, 7243, 7245, 7246, 7247, 7248, 7251, 7252, 7255, 7256, 7257, 7265, 7266, 7268, 7272, 7273, 7275, 7279, 7280, 7281, 7282, 7286, 7290, 7293, 7294, 7296, 7297, 7298, 7299, 7300, 7301, 7308, 7312, 7317, 7318, 7321, 7326, 7327, 7329, 7330, 7331, 7332, 7333, 7334, 7339, 7343, 7345, 7346, 7347, 7349, 7358, 7361, 7362, 7363, 7364, 7366, 7368, 7369, 7370, 7372, 7378, 7387, 7390, 7391, 7394, 7397, 7398, 7400, 7401, 7407, 7408, 7409, 7410, 7412, 7413, 7414, 7415, 7416, 7417, 7418, 7422, 7426, 7434, 7436, 7437, 7440, 7445, 7446, 7448, 7449, 7453, 7454, 7455, 7457, 7461, 7465, 7469, 7473, 7479, 7480, 7485, 7487, 7488, 7489, 7493, 7499, 7500, 7502, 7503, 7504, 7505, 7509, 7563, 7567, 7595, 7599, 7617, 7618, 7620, 7621, 7622, 7623, 7627, 7643, 7644, 7646, 7647, 7648, 7649, 7653, 7666, 7674, 7675, 7676, 7692, 7693, 7695, 7697, 7698, 7699, 7703, 7706, 7710, 7711, 7713, 7714, 7715, 7716, 7717, 7718, 7719, 7726, 7730, 7758, 7759, 7761, 7770, 7771, 7772, 7773, 7774, 7776, 7779, 7781, 7782, 7783, 7803, 7804, 7809, 7827, 7832, 7833, 7835, 7836, 7837, 7838, 7839, 7840, 7844, 7848, 7849, 7886, 7887, 7888, 7889, 7891, 7893, 7894, 7895, 7899, 7900, 7904, 7911, 7912, 7916, 7940, 7941, 7948, 7949, 7951, 7952, 7953, 7954, 7959, 7977, 7978, 7980, 7981, 7982, 7983, 7984, 7985, 7986, 7987, 7994, 7995, 8024, 8025, 8035, 8036, 8037, 8039, 8040, 8041, 8043, 8044, 8045, 8049, 8052, 8064, 8070, 8071, 8073, 8082, 8083, 8084, 8085, 8091, 8093, 8096, 8100, 8102, 8103, 8104, 8105, 8106, 8108, 8112, 8118, 8119, 8123, 8136, 8137, 8138, 8149, 8150, 8153, 8157, 8159, 8160, 8161, 8162, 8163, 8164, 8165, 8166, 8167, 8168, 8169, 8171, 8172, 8175, 8179, 8183, 8204, 8205, 8207, 8209, 8210, 8212, 8213, 8214, 8215, 8216, 8219, 8226, 8227, 8233, 8238, 8239, 8240, 8244, 8246, 8250, 8255, 8256, 8257, 8258, 8260, 8261, 8262, 8264, 8267, 8268, 8270, 8271, 8275, 8277, 8280, 8283, 8287, 8289, 8295, 8300, 8301, 8302, 8303, 8304, 8305, 8307, 8309, 8310, 8311, 8312, 8313, 8314, 8322, 8325, 8326, 8327, 8329, 8335, 8338, 8343, 8346, 8347, 8348, 8349, 8353, 8354, 8355, 8357, 8358, 8359, 8360, 8361, 8362, 8363, 8371, 8379, 8380, 8382, 8383, 8385, 8390, 8396, 8397, 8398, 8399, 8400, 8401, 8403, 8405, 8409, 8410, 8411, 8414, 8415, 8418, 8421, 8422, 8424, 8426, 8433, 8437, 8444, 8445, 8446, 8447, 8449, 8450, 8452, 8456, 8468, 8475, 8522, 8527, 8539, 8544, 8584, 8602, 8607, 8638, 8642, 8669, 8673, 8688, 8694, 8706, 8707, 8709, 8718, 8719, 8722, 8728, 8741, 8745, 8754, 8755, 8757, 8760, 8761, 8769, 8774, 8796, 8797, 8799, 8801, 8802, 8803, 8807, 8830, 8831, 8833, 8836, 8837, 8838, 8842, 8847, 8850, 8873, 8882, 8883, 8888, 8902, 8903, 8904, 8905, 8936, 8937, 8941, 8942, 8945, 8948, 8956, 8979, 8983, 8989, 8990, 8992, 8993, 8994, 8995, 8996, 9014, 9019, 9042, 9043, 9051, 9056, 9057, 9063, 9064, 9066, 9068, 9069, 9070, 9071, 9072, 9073, 9078, 9086, 9087, 9089, 9090, 9096, 9097, 9099, 9100, 9101, 9102, 9103, 9104, 9105, 9109, 9120, 9121, 9124, 9136, 9143, 9144, 9145, 9146, 9150, 9151, 9155, 9166, 9167, 9168, 9171, 9172, 9177, 9179, 9190, 9200, 9201, 9205, 9208, 9209, 9215, 9217, 9218, 9222, 9231, 9232, 9234, 9235, 9236, 9237, 9238, 9239, 9241, 9243, 9244, 9247, 9257, 9261, 9263, 9279, 9280, 9285, 9286, 9288, 9289, 9290, 9292, 9294, 9295, 9296, 9297, 9298, 9299, 9300, 9301, 9302, 9303, 9312, 9313, 9315, 9320, 9326, 9327, 9328, 9331, 9332, 9333, 9334, 9336, 9337, 9338, 9339, 9341, 9345, 9347, 9350, 9357, 9361, 9365, 9373, 9374, 9376, 9378, 9381, 9382, 9383, 9387, 9427]: posix_spawnp: Cannot allocate memory (system error 12), waiting a bit",
		"attributes": {
			"logger": {
				"line": 734,
				"name": "pg_wrapper.cc",
				"thread_id": 1887
			},
			"timestamp": 1655114130365,
			"level": "W"
		}
	}
}
```

**Comment by SteveXiSong** [comment]
Root cause:
1. The PG process got killed because of OOM.
2. For some reason (TBI), the new PG process cannot be started but it was neither in a failed state. Instead, it is stuck in waiting.
3. Tserver loops waiting for PG process to start (but this never happens since starting PG process was not regarded as "failed" by current logic.

**Comment by SteveXiSong** [comment]
For reference: datadog [logs](https://app.datadoghq.com/logs?agg_q=host&analyticsOptions=%5B%22bars%22%2C%22dog_classic%22%2Cnull%2Cnull%5D&event&from_ts=1655114040000&index=&live=false&query=cluster-id%3Ae0dd2601-6008-4674-90b7-792e0ab09f08+-service%3A%28yb-master+OR+cloudtrail%29+-host%3A%28i-04758ae8604bcc2c1+OR+i-0bd04816d02515c67+OR+i-0198229e4c80cc581%29&sort_m=&sort_t=&to_ts=1655114220000&top_n=10&top_o=top&viz=stream).

**Comment by kevincox** [comment]
We saw another instance of this in YugabyteDB Managed https://yugabyte.pagerduty.com/incidents/Q0VB4QMUWCE3LW

**Comment by danielcrabtree** [comment]
I've been testing Yugabyte on a development server in Docker. After unclean shutdowns, SQL connections always fail.

On digging into the logs I found:
```yb-tserver.WARNING: pg_wrapper.cc:714] PostgreSQL server exited with code 256```
```postgresql-2022-06-24_031136.log LOG:  unexpected EOF on client connection with an open transaction```

Yugabyte continues to attempt to restart the PostgreSQL layer, but it always immediately fails.

I've discovered that I can manually fix the issue by deleting: `/root/var/data/pg_data`
Yugabyte then rebuilds the pg_data folder and starts successfully.

I believe this is a different problem from the issue described in this issue. However, it does lead to tserver failing to start PG during server restart and believe it should be fixed at the same time.

I expect Yugabyte should be able to recover automatically from random power loss to a server or an unclean shutdown without manual intervention.

**Comment by SteveXiSong** [comment]
@danielcrabtree thanks for reporting such issues. We had a few fixes ongoing to address YB's stability issues as you described. 
Some of them are being fixed in #12784, #11343.

What you report looks like happened in a docker. 
As far as I learned from the platform team, docker will clean pg_data dir if restarted. From what you describe, it seems sometimes not. We will investigate it.

CC @sushantrmishra

**Comment by danielcrabtree** [comment]
On further testing (the issue has happened a few times now), there was a case where deleting the pg_data directory manually didn't resolve the problem. I suspect this may have been a race condition as after repeatedly deleting the directory and restarting the container several times, it did eventually resolve.

I think if the postgres layer fails to start, it should probably try deleting the pg_data dir before its next attempt.
