### ISSUE TITLE
[YSQL][LST] FATAL: Check failed: _s.ok() Bad status: Service unavailable (yb/rpc/reactor.cc:100): Shutdown connection (system error 108)

### ISSUE THREAD

**Issue by def-** [yugabyte/yugabyte-db#13866]
Jira Link: [DB-3368](https://yugabyte.atlassian.net/browse/DB-3368)
### Description

This happened on my first run with pessimistic locking enabled, but I believe this might have happened before, so I'm not sure if it's related to that. At least it's TxnDdl related, since `YBTxnDdlProcessUtility` is in the backtrace:
```
$ cd code/yugabyte-db
$ git checkout fabc178ef5ad0de723abc13d5d90c68773fd6c36
$ arc patch D18465
$ arc patch D18509
$ arc patch D18082
$ arc patch D18521
$ ./yb_build.sh release
$ bin/yb-ctl --replication_factor 3 create --tserver_flags=enable_pessimistic_locking=true,ysql_max_connections=20,ysql_enable_packed_row=true,yb_enable_read_committed_isolation=true,ysql_num_shards_per_tserver=2,enable_stream_compression=true,stream_compression_algo=2,yb_num_shards_per_tserver=2 --master_flags=yb_enable_read_committed_isolation=true,enable_stream_compression=true,stream_compression_algo=2,enable_automatic_tablet_splitting=true,tablet_split_low_phase_shard_count_per_node=1,tablet_split_high_phase_shard_count_per_node=5,ysql_enable_packed_row=true,enable_pessimistic_locking=true
$ cd ~/code/yb-long-system-test
$ git checkout f60b86b0ccb611c7f20adae2606a4bf99426b6fb
$ while true; do python3.9 ./long_system_test.py --nodes=127.0.0.1:5433,127.0.0.2:5433,127.0.0.3:5433 --threads=20 --runtime=60 --max-columns=20 --complexity=full; sleep 10; done
```
```
F20220905 11:02:04 ../../src/yb/yql/pggate/pggate.cc:1694] Check failed: _s.ok() Bad status: Service unavailable (yb/rpc/reactor.cc:100): Shutdown connection (system error 108)
    @     0x7fddc17836ab  google::LogMessage::SendToLog()
    @     0x7fddc17840ce  google::LogMessage::Flush()
    @     0x7fddc178685f  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fddc60117af  yb::pggate::PgApiImpl::ClearSeparateDdlTxnMode()
    @           0x9e5aa0  YBTxnDdlProcessUtility
    @           0x858eaa  PortalRunUtility
    @           0x858597  PortalRunMulti
    @           0x857e56  PortalRun
    @           0x8555d6  yb_exec_simple_query_impl
    @           0x855b76  yb_exec_query_wrapper_one_attempt
    @           0x8526eb  PostgresMain
    @           0x7be7dc  BackendRun
    @           0x7bdc30  ServerLoop
    @           0x7ba1eb  PostmasterMain
    @           0x71a79d  PostgresServerProcessMain
    @           0x71ac42  main
    @     0x7fddc58d8825  __libc_start_main
    @           0x4c7b59  _start
```
The failure was during a delete:
```
2022-09-05 10:57:24,892 MainThread INFO     Reproduce with: git checkout f60b86b0 && ./long_system_test.py --nodes=127.0.0.1:5433,127.0.0.2:5433,127.0.0.3:5433 --threads=20 --runtime=60 --max-columns=20 --complexity=full --seed=217495
2022-09-05 10:57:25,253 MainThread INFO     Database version: PostgreSQL 11.2-YB-2.15.3.0-b0 on x86_64-pc-linux-gnu, compiled by clang version 13.0.1 (https://github.com/yugabyte/llvm-project.git 0131d8e1a20f72a0f374979985db4c2871be71bc), 64-bit
2022-09-05 10:57:25,256 MainThread INFO     Creating tables for database db_lst_217495
2022-09-05 10:57:55,876 MainThread INFO     Starting worker_0: RandomSelectAction, SetConfigAction
2022-09-05 10:57:55,877 MainThread INFO     Starting worker_1: SingleInsertAction, SingleUpdateAction, SingleDeleteAction, BulkInsertAction, BulkUpdateAction, SetConfigAction
2022-09-05 10:57:55,878 MainThread INFO     Starting worker_2: CreateIndexAction, DropIndexAction, SetConfigAction, AddColumnAction
2022-09-05 10:57:55,879 MainThread INFO     Starting worker_3: SingleInsertAction, SingleUpdateAction, SingleDeleteAction, BulkInsertAction, BulkUpdateAction, SetConfigAction
2022-09-05 10:57:55,880 MainThread INFO     Starting worker_4: RandomSelectAction, SetConfigAction
2022-09-05 10:57:55,880 MainThread INFO     Starting worker_5: SingleInsertAction, SingleUpdateAction, SingleDeleteAction, BulkInsertAction, BulkUpdateAction, SetConfigAction
2022-09-05 10:57:55,885 MainThread INFO     Starting worker_6: RandomSelectAction, SetConfigAction
2022-09-05 10:57:55,887 MainThread INFO     Starting worker_7: SingleInsertAction, SingleUpdateAction, SingleDeleteAction, BulkInsertAction, BulkUpdateAction, SetConfigAction
2022-09-05 10:57:55,888 MainThread INFO     Starting worker_8: RandomSelectAction, SetConfigAction
2022-09-05 10:57:55,889 MainThread INFO     Starting worker_9: RandomSelectAction, SetConfigAction
2022-09-05 10:57:55,889 MainThread INFO     Starting worker_10: CreateIndexAction, DropIndexAction, SetConfigAction, AddColumnAction
2022-09-05 10:57:55,890 MainThread INFO     Starting worker_11: RandomSelectAction, SetConfigAction
2022-09-05 10:57:55,892 MainThread INFO     Starting worker_12: RandomSelectAction, SetConfigAction
2022-09-05 10:57:55,893 MainThread INFO     Starting worker_13: RandomSelectAction, SetConfigAction
2022-09-05 10:57:55,894 MainThread INFO     Starting worker_14: CreateIndexAction, DropIndexAction, SetConfigAction, AddColumnAction
2022-09-05 10:57:55,895 MainThread INFO     Starting worker_15: RandomSelectAction, SetConfigAction
2022-09-05 10:57:55,895 MainThread INFO     Starting worker_16: RandomSelectAction, SetConfigAction
2022-09-05 10:57:55,896 MainThread INFO     Starting worker_17: SingleInsertAction, SingleUpdateAction, SingleDeleteAction, BulkInsertAction, BulkUpdateAction, SetConfigAction
2022-09-05 10:57:55,897 MainThread INFO     Starting worker_18: RandomSelectAction, SetConfigAction
2022-09-05 10:57:55,897 MainThread INFO     Starting worker_19: SingleInsertAction, SingleUpdateAction, SingleDeleteAction, BulkInsertAction, BulkUpdateAction, SetConfigAction
2022-09-05 10:58:05,908 MainThread INFO     Worker queries/s: [000.3][006.0][000.2][001.4][000.3][001.7][000.8][001.4][000.8][000.3][000.2][001.9][001.2][001.7][000.1][000.8][000.1][000.9][000.9][004.9]
2022-09-05 10:58:15,919 MainThread INFO     Worker queries/s: [000.9][007.6][000.2][003.9][000.7][003.5][000.9][003.8][002.9][001.2][000.0][005.6][005.2][004.1][000.1][004.5][000.4][002.3][005.3][010.7]
2022-09-05 10:58:25,933 MainThread INFO     Worker queries/s: [000.4][003.6][000.3][001.9][000.6][001.5][001.0][002.3][001.7][000.8][000.0][002.7][001.7][002.3][000.3][001.8][000.2][001.5][001.8][002.6]
2022-09-05 10:58:35,943 MainThread INFO     Worker queries/s: [000.2][005.3][000.6][001.0][000.5][002.0][000.8][003.2][002.5][000.5][000.0][003.0][002.6][001.9][000.0][002.6][000.4][002.0][001.9][004.2]
2022-09-05 10:58:45,953 MainThread INFO     Worker queries/s: [000.7][006.7][000.1][002.6][000.5][002.1][000.8][002.6][004.1][000.9][000.0][003.4][004.4][002.8][000.0][003.2][000.7][004.7][003.0][005.0]
2022-09-05 10:58:55,963 MainThread INFO     Worker queries/s: [000.4][004.6][000.5][001.2][000.3][001.8][000.8][001.9][002.0][000.6][000.0][002.1][003.0][002.6][000.1][002.0][000.4][000.1][001.7][001.4]
2022-09-05 10:59:05,975 MainThread INFO     Worker queries/s: [000.6][006.9][000.0][005.9][001.1][002.1][001.0][004.3][003.9][000.3][000.2][004.3][005.9][005.8][000.0][003.4][000.9][002.6][003.7][008.2]
2022-09-05 10:59:15,986 MainThread INFO     Worker queries/s: [000.4][005.1][000.3][002.8][000.6][001.9][000.5][002.4][003.1][000.6][000.1][002.3][002.8][002.4][000.4][002.1][000.7][002.0][001.7][005.5]
2022-09-05 10:59:26,004 MainThread INFO     Worker queries/s: [000.6][003.9][000.1][003.2][000.5][001.4][001.0][002.0][002.0][000.4][000.5][001.5][002.4][001.4][000.3][001.9][000.4][002.1][001.9][003.5]
2022-09-05 10:59:36,014 MainThread INFO     Worker queries/s: [000.1][003.0][000.3][001.8][000.5][002.4][000.7][002.4][001.9][000.8][000.4][001.9][002.1][002.0][000.1][001.7][000.7][002.0][001.8][003.2]
2022-09-05 10:59:46,030 MainThread INFO     Worker queries/s: [000.6][003.9][000.2][003.2][000.2][001.4][000.4][001.6][001.5][000.5][000.2][002.1][002.6][001.7][000.4][001.9][000.3][002.7][001.7][003.4]
2022-09-05 10:59:56,040 MainThread INFO     Worker queries/s: [000.5][003.3][000.3][003.2][000.5][001.8][000.4][002.4][001.8][000.7][000.8][001.8][002.5][002.1][000.0][001.8][000.2][002.3][001.9][004.8]
2022-09-05 11:00:06,050 MainThread INFO     Worker queries/s: [000.5][004.0][000.2][001.1][000.4][001.8][000.7][000.2][003.7][000.9][000.0][002.6][002.8][003.2][000.0][002.1][000.2][000.0][002.2][007.8]
2022-09-05 11:00:16,060 MainThread INFO     Worker queries/s: [000.6][000.0][000.2][000.0][000.6][002.6][000.7][000.0][002.7][000.6][000.2][002.4][002.7][002.6][000.0][002.5][000.9][000.0][002.6][006.1]
2022-09-05 11:00:26,070 MainThread INFO     Worker queries/s: [001.0][000.0][000.1][000.0][000.8][005.8][000.8][000.0][004.1][000.5][000.0][004.7][004.3][003.1][000.3][002.8][000.7][000.0][002.4][000.0]
2022-09-05 11:00:36,086 MainThread INFO     Worker queries/s: [000.4][002.6][000.3][000.3][000.5][001.5][000.8][001.6][001.9][000.6][000.2][002.4][002.0][002.4][000.3][001.8][000.5][002.7][001.6][000.2]
2022-09-05 11:00:46,096 MainThread INFO     Worker queries/s: [000.4][002.2][000.5][000.7][000.1][002.2][000.5][000.7][001.4][000.8][000.2][001.5][002.4][001.9][000.0][001.7][000.1][001.8][001.3][001.7]
2022-09-05 11:00:56,106 MainThread INFO     Worker queries/s: [000.4][004.6][000.0][003.2][000.5][002.1][001.0][001.5][001.2][000.6][000.0][001.6][001.9][002.3][000.5][001.5][000.9][002.0][002.2][003.5]
2022-09-05 11:01:06,116 MainThread INFO     Worker queries/s: [000.4][002.6][000.2][002.0][000.3][001.3][000.7][001.7][002.3][000.6][000.3][003.2][002.4][002.6][000.0][001.8][000.6][001.7][002.4][003.5]
2022-09-05 11:01:16,128 MainThread INFO     Worker queries/s: [000.0][005.3][000.1][003.3][000.4][002.1][000.8][000.1][002.3][000.5][000.3][001.9][001.9][002.0][000.5][001.9][000.5][003.5][001.5][006.2]
2022-09-05 11:01:26,147 MainThread INFO     Worker queries/s: [000.2][005.5][001.0][001.6][000.5][002.3][000.6][002.0][001.4][000.4][000.0][001.9][001.6][001.2][000.1][002.1][000.4][002.1][002.2][003.5]
2022-09-05 11:01:36,157 MainThread INFO     Worker queries/s: [000.5][005.0][000.5][001.9][000.6][002.1][000.2][002.7][001.6][001.2][000.1][002.7][002.3][001.4][000.4][002.4][000.0][004.5][002.0][004.5]
2022-09-05 11:01:46,167 MainThread INFO     Worker queries/s: [000.3][001.6][000.6][000.6][000.0][000.4][000.4][000.5][000.3][000.3][000.1][000.7][000.7][000.8][000.1][000.9][000.2][000.7][001.1][001.2]
2022-09-05 11:01:56,177 MainThread INFO     Worker queries/s: [000.0][000.0][000.0][000.0][000.0][000.0][000.0][000.0][000.0][000.0][000.0][000.0][000.0][000.0][000.0][000.0][000.0][000.0][000.0][000.0]
2022-09-05 11:01:56,473 worker_17  ERROR    Unexpected query failure: ConnectionFailure
Query: DELETE FROM tg0_1 WHERE TRUE;
  values: None
  runtime: 2022-09-05 11:01:41.280 - 2022-09-05 11:01:56.473
  supports explain: True
  supports rollback: True
  affected rows: None
Action: SingleDeleteAction
Error class: ConnectionFailure
Error code: 08006
Error message: FATAL:  Could not reconnect to database
    @           0x9b6628  errmsg
    @           0x996e4a  YBPreloadRelCache
    @           0x854f35  YBPreloadRelCacheHelper
    @           0x854d5d  YBRefreshCache
    @           0x850ecf  PostgresMain
    @           0x7be7dc  BackendRun
    @           0x7bdc30  ServerLoop
    @           0x7ba1eb  PostmasterMain
    @           0x71a79d  PostgresServerProcessMain
    @           0x71ac42  main
    @     0x7fddc58d8825  __libc_start_main
    @           0x4c7b59  _start

HINT:  Database might have been dropped by another user
    @           0x9b7ce8  errhint
    @           0x996e5a  YBPreloadRelCache
    @           0x854f35  YBPreloadRelCacheHelper
    @           0x854d5d  YBRefreshCache
    @           0x850ecf  PostgresMain
    @           0x7be7dc  BackendRun
    @           0x7bdc30  ServerLoop
    @           0x7ba1eb  PostmasterMain
    @           0x71a79d  PostgresServerProcessMain
    @           0x71ac42  main
    @     0x7fddc58d8825  __libc_start_main
    @           0x4c7b59  _start

server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
Transaction isolation level: read uncommitted
DB Node: host: 127.0.0.3, port: 5433
DB Backend PID: 2637528
```
LST logs: [lst_2022-09-05_10:57:24_217495.zip](https://github.com/yugabyte/yugabyte-db/files/9489236/lst_2022-09-05_10.57.24_217495.zip)
yugabyte-data directory, accessible from within Yugabyte org: https://drive.google.com/file/d/1wtEm2LD1-b-Yg55LSjtJTCvLZCYABxX_/view?usp=sharing
Similar bug before, maybe we should consider this a duplicate if there is nothing pessimistic-locking specific in this failure: https://github.com/yugabyte/yugabyte-db/issues/13071

**Comment by def-** [comment]
Looks unrelated to pessimistic locking

**Comment by def-** [comment]
Also failed in upgrade test `testupgrade-aws-rf3-upgrade-2.14.4.0_26` to 2.17.0.0:

```
F20221110 00:26:17 ../../src/yb/yql/pggate/pggate.cc:1726] Check failed: _s.ok() Bad status: Aborted (yb/rpc/reactor.cc:94): Shutdown connection (system error 108)
    @     0x7fba9ae94e1c  google::LogDestination::LogToSinks()
    @     0x7fba9ae94844  google::LogMessage::SendToLog()
    @     0x7fba9ae95fd8  google::LogMessage::Flush()
    @     0x7fba9ae967bf  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fba9fee6cef  yb::pggate::PgApiImpl::ClearSeparateDdlTxnMode()
    @           0xb258cf  YBTxnDdlProcessUtility
    @           0x95c594  PortalRunUtility
    @           0x95c367  PortalRunMulti
    @           0x95b923  PortalRun
    @           0x9576d6  yb_exec_simple_query_impl
    @           0x957e94  yb_exec_query_wrapper_one_attempt
    @           0x95444b  PostgresMain
    @           0x8afd5b  BackendRun
    @           0x8af45a  ServerLoop
    @           0x8abab1  PostmasterMain
    @           0x7cb233  PostgresServerProcessMain
    @           0x4f73f2  main
    @     0x7fba9eeb2825  __libc_start_main
    @           0x4f72f9  _start
    @              (nil)  (unknown)
```

**Comment by def-** [comment]
The failure there already happens before the upgrade, after creating backup:
```
testupgrade-aws-rf3-upgrade-2.14.4.0_26: Start
    (     1.014s) User Login : Success
    (     0.907s) Refresh YB Version : Success
    (   130.183s) Setup Provider : Success
    (     1.271s) Updating Health Check Interval to 60000 sec : Success
    (   305.135s) Create universe jenk-is2057-ab82e91545-20221109-133110 : Success
    (    55.054s) Start sample workloads : Success
    (  1644.774s) Creating V2 backups in S3 : Success
    (   312.278s) Check for fatals : >>> Integration Test Failed <<<
Found FATAL log file in 10.9.136.57/tserver.
(    31.476s) Saved server log files and keys at /share/jenkins/workspace/itest-system/logs/2.17.0.0_testupgrade-aws-rf3-upgrade-2.14.4.0_26_20221110_002709 : Success
(    36.065s) Saved server log files and keys at /share/jenkins/workspace/itest-system/logs/2.17.0.0_testupgrade-aws-rf3-upgrade-2.14.4.0_26_20221110_002745 : Success
(     0.000s) Saved server log files and keys at /share/jenkins/workspace/itest-system/logs/2.17.0.0_testupgrade-aws-rf3-upgrade-2.14.4.0_26_20221110_002745 : Hit error before destroying universe 'jenk-is2057-ab82e91545-20221109-133110':
Found FATAL log file in 10.9.136.57/tserver.
(   120.960s) Destroy universe : Success
(     0.369s) Check and stop workloads : Success
testupgrade-aws-rf3-upgrade-2.14.4.0_26: End
```

**Comment by fizaaluthra** [comment]
Closing as part of #13128  -- addressed in commit 5a6d54a6995b3d45dbba257abde296e91fa63e54

**Comment by rjalan-yb** [comment]
Hey @fizaaluthra , this issue is still seen on 2.19.0.0-b155 upgrade tests. This is very frequently reproducible:

https://jenkins.dev.yugabyte.com/job/itest-system-developer/7411/artifact/logs/2.19.1.0_testupgraderolling-aws-rf3-upgrade-preferred_zone-2.18.1.0-b84_20230718_233828/10.9.198.64/
