### ISSUE TITLE
YSQL Catalog Query error whilst creating tables

### ISSUE THREAD

**Issue by mrpanda** [YugaByte/yugabyte-db#1648]
Not serious but might mean there is something else going on that is not good --
I am running 2 sessions, 1 session is dropping a table if it exists, then creating it, the other session is checking the information_catalog for a table count. I occasionally receive an error when I perform a query of the information_schema.

The SQL: select count(*) from information_schema.tables where table_schema = 'public';

The Error: 
ERROR:  Query error: Catalog Version Mismatch: A DDL occurred while processing this query. Try Again.

**Comment by kmuthukk** [comment]
Thx for reporting @mrpanda .

This is a known issue (#1457) that we are actively working on a fix for.

**Comment by ttyusupov** [comment]
@mrpanda , #1457 has been fixed, can you try with the latest version?

**Comment by mrpanda** [comment]
Hi, I still have the old version installed so I won't be able to get round to testing this for about a week. But I will.... Thanks.

**Comment by ttyusupov** [comment]
Hi @mrpanda , did you have a chance to try with version 1.3?

**Comment by ndeodhar** [comment]
Hi @mrpanda, I’m closing this issue since it’s fixed in 1.3. Please feel free to reopen if this persists for you even after upgrading.
