### ISSUE TITLE
[DocDB] TSAN race in YbAdminSnapshotScheduleTest.ListRestorationsAfterFailover

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#17831]
Jira Link: [DB-6919](https://yugabyte.atlassian.net/browse/DB-6919)
### Description

Example log: https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-centos-master-clang15-tsan/1548/artifact/build/tsan-clang15-dynamic-ninja/yb-test-logs/tests-tools__yb-admin-snapshot-schedule-test/YbAdminSnapshotScheduleTest_ListRestorationsAfterFailover.log

```
[m-2] WARNING: ThreadSanitizer: data race (pid=6984)
[m-2]   Write of size 8 at 0x7b8000200a60 by thread T2 (mutexes: write M0, write M1):
[m-2]     #0 std::__bit_reference<std::__bitset<1ul, 6ul>, true>::operator=[abi:v15007](bool) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20230519215552-04b5c61ec3-centos7-x86_64-clang15/installed/tsan/libcxx/include/c++/v1/__bit_reference (libtablet.so+0x293d09)
[m-2]     #1 std::bitset<6ul>::set(unsigned long, bool) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20230519215552-04b5c61ec3-centos7-x86_64-clang15/installed/tsan/libcxx/include/c++/v1/bitset:880:20 (libtablet.so+0x293d09)
[m-2]     #2 yb::EnumBitSet<yb::consensus::ReplicateMsgFields>::Set(yb::consensus::ReplicateMsgFields, bool) ${BUILD_ROOT}/../../src/yb/util/enums.h:331:11 (libtablet.so+0x293d09)
[m-2]     #3 yb::consensus::LWReplicateMsg::mutable_id() ${BUILD_ROOT}/src/yb/consensus/consensus.messages.h:743:17 (libtablet.so+0x293d09)
[m-2]     #4 yb::tablet::Operation::AddedToLeader(yb::OpId const&, yb::OpId const&) ${BUILD_ROOT}/../../src/yb/tablet/operations/operation.cc:141:31 (libtablet.so+0x293d09)
[m-2]     #5 yb::tablet::OperationDriver::AddedToLeader(yb::OpId const&, yb::OpId const&) ${BUILD_ROOT}/../../src/yb/tablet/operations/operation_driver.cc:208:3 (libtablet.so+0x2a9b46)
[m-2]     #6 yb::consensus::ConsensusRound::NotifyAddedToLeader(yb::OpId const&, yb::OpId const&) ${BUILD_ROOT}/../../src/yb/consensus/consensus_round.cc:37:21 (libconsensus.so+0xc43f5)
[m-2]     #7 yb::consensus::RaftConsensus::DoAppendNewRoundsToQueueUnlocked(std::vector<scoped_refptr<yb::consensus::ConsensusRound>, std::allocator<scoped_refptr<yb::consensus::ConsensusRound>>> const&, unsigned long*, std::vector<std::shared_ptr<yb::consensus::LWReplicateMsg>, std::allocator<std::shared_ptr<yb::consensus::LWReplicateMsg>>>*) ${BUILD_ROOT}/../../src/yb/consensus/raft_consensus.cc:1300:5 (libconsensus.so+0xf6906)
[m-2]     #8 yb::consensus::RaftConsensus::AppendNewRoundsToQueueUnlocked(std::vector<scoped_refptr<yb::consensus::ConsensusRound>, std::allocator<scoped_refptr<yb::consensus::ConsensusRound>>> const&, unsigned long*) ${BUILD_ROOT}/../../src/yb/consensus/raft_consensus.cc:1245:17 (libconsensus.so+0xf61ba)
[m-2]     #9 yb::consensus::RaftConsensus::DoReplicateBatch(std::vector<scoped_refptr<yb::consensus::ConsensusRound>, std::allocator<scoped_refptr<yb::consensus::ConsensusRound>>> const&, unsigned long*) ${BUILD_ROOT}/../../src/yb/consensus/raft_consensus.cc:1191:5 (libconsensus.so+0xf5876)
[m-2]     #10 yb::consensus::RaftConsensus::ReplicateBatch(std::vector<scoped_refptr<yb::consensus::ConsensusRound>, std::allocator<scoped_refptr<yb::consensus::ConsensusRound>>> const&) ${BUILD_ROOT}/../../src/yb/consensus/raft_consensus.cc:1159:17 (libconsensus.so+0xf52ab)
[m-2]     #11 yb::tablet::PreparerImpl::ReplicateSubBatch(std::__wrap_iter<yb::tablet::OperationDriver**>, std::__wrap_iter<yb::tablet::OperationDriver**>) ${BUILD_ROOT}/../../src/yb/tablet/preparer.cc:388:32 (libtablet.so+0x2ec8c8)
[m-2]     #12 yb::tablet::PreparerImpl::ProcessAndClearLeaderSideBatch() ${BUILD_ROOT}/../../src/yb/tablet/preparer.cc:353:3 (libtablet.so+0x2ec0e6)
[m-2]     #13 yb::tablet::PreparerImpl::Run() ${BUILD_ROOT}/../../src/yb/tablet/preparer.cc:217:5 (libtablet.so+0x2eb60e)
[m-2]     #14 decltype(*std::declval<yb::tablet::PreparerImpl*&>().*std::declval<void (yb::tablet::PreparerImpl::*&)()>()()) std::__invoke[abi:v15007]<void (yb::tablet::PreparerImpl::*&)(), yb::tablet::PreparerImpl*&, void>(void (yb::tablet::PreparerImpl::*&)(), yb::tablet::PreparerImpl*&) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20230519215552-04b5c61ec3-centos7-x86_64-clang15/installed/tsan/libcxx/include/c++/v1/__functional/invoke.h:359:23 (libtablet.so+0x2edd7b)
[m-2]     #15 std::__bind_return<void (yb::tablet::PreparerImpl::*)(), std::tuple<yb::tablet::PreparerImpl*>, std::tuple<>, __is_valid_bind_return<void (yb::tablet::PreparerImpl::*)(), std::tuple<yb::tablet::PreparerImpl*>, std::tuple<>>::value>::type std::__apply_functor[abi:v15007]<void (yb::tablet::PreparerImpl::*)(), std::tuple<yb::tablet::PreparerImpl*>, 0ul, std::tuple<>>(void (yb::tablet::PreparerImpl::*&)(), std::tuple<yb::tablet::PreparerImpl*>&, std::__tuple_indices<0ul>, std::tuple<>&&) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20230519215552-04b5c61ec3-centos7-x86_64-clang15/installed/tsan/libcxx/include/c++/v1/__functional/bind.h:263:12 (libtablet.so+0x2edd7b)
[m-2]     #16 std::__bind_return<void (yb::tablet::PreparerImpl::*)(), std::tuple<yb::tablet::PreparerImpl*>, std::tuple<>, __is_valid_bind_return<void (yb::tablet::PreparerImpl::*)(), std::tuple<yb::tablet::PreparerImpl*>, std::tuple<>>::value>::type std::__bind<void (yb::tablet::PreparerImpl::*)(), yb::tablet::PreparerImpl*>::operator()[abi:v15007]<>() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20230519215552-04b5c61ec3-centos7-x86_64-clang15/installed/tsan/libcxx/include/c++/v1/__functional/bind.h:295:20 (libtablet.so+0x2edd7b)
[m-2]     #17 decltype(std::declval<std::__bind<void (yb::tablet::PreparerImpl::*)(), yb::tablet::PreparerImpl*>&>()()) std::__invoke[abi:v15007]<std::__bind<void (yb::tablet::PreparerImpl::*)(), yb::tablet::PreparerImpl*>&>(std::__bind<void (yb::tablet::PreparerImpl::*)(), yb::tablet::PreparerImpl*>&) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20230519215552-04b5c61ec3-centos7-x86_64-clang15/installed/tsan/libcxx/include/c++/v1/__functional/invoke.h:394:23 (libtablet.so+0x2edd7b)
[m-2]     #18 void std::__invoke_void_return_wrapper<void, true>::__call<std::__bind<void (yb::tablet::PreparerImpl::*)(), yb::tablet::PreparerImpl*>&>(std::__bind<void (yb::tablet::PreparerImpl::*)(), yb::tablet::PreparerImpl*>&) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20230519215552-04b5c61ec3-centos7-x86_64-clang15/installed/tsan/libcxx/include/c++/v1/__functional/invoke.h:479:9 (libtablet.so+0x2edd7b)
[m-2]     #19 std::__function::__alloc_func<std::__bind<void (yb::tablet::PreparerImpl::*)(), yb::tablet::PreparerImpl*>, std::allocator<std::__bind<void (yb::tablet::PreparerImpl::*)(), yb::tablet::PreparerImpl*>>, void ()>::operator()[abi:v15007]() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20230519215552-04b5c61ec3-centos7-x86_64-clang15/installed/tsan/libcxx/include/c++/v1/__functional/function.h:185:16 (libtablet.so+0x2edd7b)
[m-2]     #20 std::__function::__func<std::__bind<void (yb::tablet::PreparerImpl::*)(), yb::tablet::PreparerImpl*>, std::allocator<std::__bind<void (yb::tablet::PreparerImpl::*)(), yb::tablet::PreparerImpl*>>, void ()>::operator()() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20230519215552-04b5c61ec3-centos7-x86_64-clang15/installed/tsan/libcxx/include/c++/v1/__functional/function.h:359:12 (libtablet.so+0x2edd7b)
[m-2]     #21 std::__function::__value_func<void ()>::operator()[abi:v15007]() const /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20230519215552-04b5c61ec3-centos7-x86_64-clang15/installed/tsan/libcxx/include/c++/v1/__functional/function.h:512:16 (libyb_util.so+0x37a774)
[m-2]     #22 std::function<void ()>::operator()() const /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20230519215552-04b5c61ec3-centos7-x86_64-clang15/installed/tsan/libcxx/include/c++/v1/__functional/function.h:1197:12 (libyb_util.so+0x37a774)
[m-2]     #23 yb::FunctionRunnable::Run() ${BUILD_ROOT}/../../src/yb/util/threadpool.h:510:5 (libyb_util.so+0x37a774)
[m-2]     #24 yb::ThreadPool::DispatchThread(bool) ${BUILD_ROOT}/../../src/yb/util/threadpool.cc:612:22 (libyb_util.so+0x377493)
[m-2]     #25 decltype(*std::declval<yb::ThreadPool*&>().*std::declval<void (yb::ThreadPool::*&)(bool)>()(std::declval<bool&>())) std::__invoke[abi:v15007]<void (yb::ThreadPool::*&)(bool), yb::ThreadPool*&, bool&, void>(void (yb::ThreadPool::*&)(bool), yb::ThreadPool*&, bool&) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20230519215552-04b5c61ec3-centos7-x86_64-clang15/installed/tsan/libcxx/include/c++/v1/__functional/invoke.h:359:23 (libyb_util.so+0x37f338)
[m-2]     #26 std::__bind_return<void (yb::ThreadPool::*)(bool), std::tuple<yb::ThreadPool*, bool>, std::tuple<>, __is_valid_bind_return<void (yb::ThreadPool::*)(bool), std::tuple<yb::ThreadPool*, bool>, std::tuple<>>::value>::type std::__apply_functor[abi:v15007]<void (yb::ThreadPool::*)(bool), std::tuple<yb::ThreadPool*, bool>, 0ul, 1ul, std::tuple<>>(void (yb::ThreadPool::*&)(bool), std::tuple<yb::ThreadPool*, bool>&, std::__tuple_indices<0ul, 1ul>, std::tuple<>&&) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20230519215552-04b5c61ec3-centos7-x86_64-clang15/installed/tsan/libcxx/include/c++/v1/__functional/bind.h:263:12 (libyb_util.so+0x37f338)
[m-2]     #27 std::__bind_return<void (yb::ThreadPool::*)(bool), std::tuple<yb::ThreadPool*, bool>, std::tuple<>, __is_valid_bind_return<void (yb::ThreadPool::*)(bool), std::tuple<yb::ThreadPool*, bool>, std::tuple<>>::value>::type std::__bind<void (yb::ThreadPool::* const&)(bool), yb::ThreadPool* const&, bool const&>::operator()[abi:v15007]<>() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20230519215552-04b5c61ec3-centos7-x86_64-clang15/installed/tsan/libcxx/include/c++/v1/__functional/bind.h:295:20 (libyb_util.so+0x37f338)
[m-2]     #28 decltype(std::declval<std::__bind<void (yb::ThreadPool::* const&)(bool), yb::ThreadPool* const&, bool const&>&>()()) std::__invoke[abi:v15007]<std::__bind<void (yb::ThreadPool::* const&)(bool), yb::ThreadPool* const&, bool const&>&>(std::__bind<void (yb::ThreadPool::* const&)(bool), yb::ThreadPool* const&, bool const&>&) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20230519215552-04b5c61ec3-centos7-x86_64-clang15/installed/tsan/libcxx/include/c++/v1/__functional/invoke.h:394:23 (libyb_util.so+0x37f338)
[m-2]     #29 void std::__invoke_void_return_wrapper<void, true>::__call<std::__bind<void (yb::ThreadPool::* const&)(bool), yb::ThreadPool* const&, bool const&>&>(std::__bind<void (yb::ThreadPool::* const&)(bool), yb::ThreadPool* const&, bool const&>&) /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20230519215552-04b5c61ec3-centos7-x86_64-clang15/installed/tsan/libcxx/include/c++/v1/__functional/invoke.h:479:9 (libyb_util.so+0x37f338)
[m-2]     #30 std::__function::__alloc_func<std::__bind<void (yb::ThreadPool::* const&)(bool), yb::ThreadPool* const&, bool const&>, std::allocator<std::__bind<void (yb::ThreadPool::* const&)(bool), yb::ThreadPool* const&, bool const&>>, void ()>::operator()[abi:v15007]() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20230519215552-04b5c61ec3-centos7-x86_64-clang15/installed/tsan/libcxx/include/c++/v1/__functional/function.h:185:16 (libyb_util.so+0x37f338)
[m-2]     #31 std::__function::__func<std::__bind<void (yb::ThreadPool::* const&)(bool), yb::ThreadPool* const&, bool const&>, std::allocator<std::__bind<void (yb::ThreadPool::* const&)(bool), yb::ThreadPool* const&, bool const&>>, void ()>::operator()() /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20230519215552-04b5c61ec3-centos7-x86_64-clang15/installed/tsan/libcxx/include/c++/v1/__functional/function.h:359:12 (libyb_util.so+0x37f338)
[m-2]     #32 std::__function::__value_func<void ()>::operator()[abi:v15007]() const /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20230519215552-04b5c61ec3-centos7-x86_64-clang15/installed/tsan/libcxx/include/c++/v1/__functional/function.h:512:16 (libyb_util.so+0x364d0a)
[m-2]     #33 std::function<void ()>::operator()() const /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20230519215552-04b5c61ec3-centos7-x86_64-clang15/installed/tsan/libcxx/include/c++/v1/__functional/function.h:1197:12 (libyb_util.so+0x364d0a)
[m-2]     #34 yb::Thread::SuperviseThread(void*) ${BUILD_ROOT}/../../src/yb/util/thread.cc:842:3 (libyb_util.so+0x364d0a)
[m-2] 
[m-2]   Previous read of size 8 at 0x7b8000200a60 by thread T118 (mutexes: write M2):
[m-2]     #0 std::__bit_const_reference<std::__bitset<1ul, 6ul>>::operator bool[abi:v15007]() const /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20230519215552-04b5c61ec3-centos7-x86_64-clang15/installed/tsan/libcxx/include/c++/v1/__bit_reference:163:35 (libconsensus_proto.so+0xf8109)
[m-2]     #1 std::bitset<6ul>::test(unsigned long) const /opt/yb-build/thirdparty/yugabyte-db-thirdparty-v20230519215552-04b5c61ec3-centos7-x86_64-clang15/installed/tsan/libcxx/include/c++/v1/bitset:1022:12 (libconsensus_proto.so+0xf8109)
[m-2]     #2 yb::EnumBitSet<yb::consensus::ReplicateMsgFields>::Test(yb::consensus::ReplicateMsgFields) const ${BUILD_ROOT}/../../src/yb/util/enums.h:311:18 (libconsensus_proto.so+0xf8109)
[m-2]     #3 yb::consensus::LWReplicateMsg::has_id() const ${BUILD_ROOT}/src/yb/consensus/consensus.messages.h:748:24 (libconsensus_proto.so+0xf8109)
[m-2]     #4 yb::consensus::LWReplicateMsg::AppendToDebugString(string*) const ${BUILD_ROOT}/src/yb/consensus/consensus.messages.cc:654:7 (libconsensus_proto.so+0xf8109)
[m-2]     #5 yb::rpc::LightweightMessage::ShortDebugString() const ${BUILD_ROOT}/../../src/yb/rpc/lightweight_message.cc:93:3 (libyrpc_base.so+0x6a4b)
[m-2]     #6 yb::consensus::ConsensusRound::ToString() const ${BUILD_ROOT}/../../src/yb/consensus/consensus_round.cc:64:26 (libconsensus.so+0xc47ba)
[m-2]     #7 std::enable_if<HasMemberFunction_ToString<yb::consensus::ConsensusRound>::value, string>::type yb::ToString<yb::consensus::ConsensusRound>(yb::consensus::ConsensusRound const&) ${BUILD_ROOT}/../../src/yb/util/tostring.h:75:16 (libtablet.so+0x296000)
```

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6919]: https://yugabyte.atlassian.net/browse/DB-6919?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by robertsami** [comment]
looks like a similar issue to the one addressed in 8312e9bdc1a81043fc059bfdeaf67b2314d3ffa8

**Comment by bmatican** [comment]
Still seeing this in
YbAdminSnapshotScheduleTest.PgsqlRestoreDroppedTableWithTablespace
YbAdminSnapshotScheduleTest.ListRestorationsTestMigration
YbAdminSnapshotScheduleTest.ListRestorationsAfterFailover

**Comment by bmatican** [comment]
Sergei could you take a stab at this and also add some thread safety annotations to Operation and OperationDriver, for future proofing & clarifying class expectations?
