### ISSUE TITLE
[yugabyted] killing yb-tserver twice crashes yugabyted parent process

### ISSUE THREAD

**Issue by kmuthukk** [yugabyte/yugabyte-db#3207]
1. Started yugabytedb
2. kill -9 <yb-tserver>
3. The parent process auto restarted the yb-tserver.
4. kill -9 <yb-tserver>  again, but this time it takes down the parent process also.

**Comment by kmuthukk** [comment]
[logs.tar.gz](https://github.com/yugabyte/yugabyte-db/files/3990558/logs.tar.gz)

**Comment by iSignal** [comment]
@kmuthukk , if you still have the logs from this test, please re attach them by running: 

`tar -cvhf logs.tar.gz ui/logs/ yugabyte-logs/` (otherwise symlinked master and tserver logs werent captured).

If you don't have this test dir around any longer, feel free to ignore.

**Comment by WesleyW** [comment]
Fixed as part of 07f07aa, was a problem with YSQL/DocDB mismatch

**Comment by iSignal** [comment]
Repro is timing dependent, but it will still happen if we do kill tserver during the is_yw_initialized check in the loop.
