### ISSUE TITLE
[YSQL] Support cube extension

### ISSUE THREAD

**Issue by frozenspider** [yugabyte/yugabyte-db#3628]
```
-- Support to multi-dimensional cubes
CREATE EXTENSION IF NOT EXISTS "cube";
```

See related issue (for extensions in general): #1154

**Comment by frozenspider** [comment]
After #2711, `cube` extension works - with the exception that you can't apply `ORDER BY` to a `cube` column:
```
yugabyte=# CREATE TABLE test_cube (c cube);
CREATE TABLE
yugabyte=# SELECT * FROM test_cube WHERE c && '(3000,1000),(0,0)' ORDER BY c;
ERROR:  could not identify an ordering operator for type cube
LINE 1: ... * FROM test_cube WHERE c && '(3000,1000),(0,0)' ORDER BY c;
                                                                     ^
HINT:  Use an explicit ordering operator or modify the query.
```

**Comment by ddorian** [comment]
Same error happens on 2.2.2.0

**Comment by shaunstoltz** [comment]
This resolved by pr https://github.com/yugabyte/yugabyte-db/pull/9576

**Comment by ddorian** [comment]
The error in https://github.com/yugabyte/yugabyte-db/issues/3628#issuecomment-599811879 still persists in 2.9.0.0
