### ISSUE TITLE
Windows 10: Creation of Docker Container fails

### ISSUE THREAD

**Issue by walter-weinmann** [yugabyte/yugabyte-db#5497]
#### Docker Desktop: 2.3.0.4 (46911) Channel: stable

```
D:\SoftDevelopment\Projects\Konnexions\db_seeder>docker run -d --name yugabyte -p7000:7000 -p9001:9000 -p5433:5433 -p9042:9042 -v %cd%/tmp/yb_data:/home/yugabyte/var yugabytedb/yugabyte:latest bin/yugabyted start --daemon=false
Unable to find image 'yugabytedb/yugabyte:latest' locally
latest: Pulling from yugabytedb/yugabyte
524b0c1e57f8: Already exists
b5318e0f4ff7: Pull complete
ca1b70db4153: Pull complete
4391f253e700: Pull complete
69b55db65312: Pull complete
d8fab475d8f7: Pull complete
Digest: sha256:c0f92818c459f47a89f2f45a71af5702d26c6ff312af346c96f2579524cc5914
Status: Downloaded newer image for yugabytedb/yugabyte:latest
ba5a177bca9c2caf604fae8f97697bab95f3ea0963563b57ae1fcf8773d73c14

D:\SoftDevelopment\Projects\Konnexions\db_seeder>docker ps
CONTAINER ID        IMAGE                 COMMAND             CREATED             STATUS              PORTS                                            NAMES
edee6f7e1435        portainer/portainer   "/portainer"        4 weeks ago         Up 25 hours         0.0.0.0:8000->8000/tcp, 0.0.0.0:9000->9000/tcp   portainer

D:\SoftDevelopment\Projects\Konnexions\db_seeder>
```

#### Structure of the YugabyteDB directory:

![image](https://user-images.githubusercontent.com/1956149/91274176-97fc2080-e77e-11ea-8589-2b366ac8252f.png)

![image](https://user-images.githubusercontent.com/1956149/91274248-b2ce9500-e77e-11ea-8c64-9b52ed8613af.png)

![image](https://user-images.githubusercontent.com/1956149/91274312-c7129200-e77e-11ea-9993-5109cfda858d.png)

![image](https://user-images.githubusercontent.com/1956149/91274406-ec9f9b80-e77e-11ea-858e-56d8eebd90a3.png)

#### Content of master.err:

```
F0826 07:12:39.977998    15 master_main.cc:120] Not found (yb/util/env_posix.cc:1482): Unable to initialize catalog manager: Failed to initialize sys tables async: Failed to open new log: /home/yugabyte/var/data/yb-data/master/wals/table-sys.catalog.uuid/tablet-00000000000000000000000000000000/wal-000000001: No such file or directory (system error 2)
Fatal failure details written to /home/yugabyte/var/data/yb-data/master/logs/yb-master.FATAL.details.2020-08-26T07_12_39.pid15.txt
F20200826 07:12:39 ../../src/yb/master/master_main.cc:120] Not found (yb/util/env_posix.cc:1482): Unable to initialize catalog manager: Failed to initialize sys tables async: Failed to open new log: /home/yugabyte/var/data/yb-data/master/wals/table-sys.catalog.uuid/tablet-00000000000000000000000000000000/wal-000000001: No such file or directory (system error 2)
    @     0x7f3e8de7a5fc  yb::LogFatalHandlerSink::send()
    @     0x7f3e8d05a376  google::LogMessage::SendToLog()
    @     0x7f3e8d0577da  google::LogMessage::Flush()
    @     0x7f3e8d05a8a9  google::LogMessageFatal::~LogMessageFatal()
    @           0x409224  yb::master::MasterMain()
    @     0x7f3e88cb0825  __libc_start_main
    @           0x4085d9  _start
    @              (nil)  (unknown)

*** Check failure stack trace: ***
    @     0x7f3e8de789e1  yb::(anonymous namespace)::DumpStackTraceAndExit()
    @     0x7f3e8d057c8d  google::LogMessage::Fail()
    @     0x7f3e8d059dfd  google::LogMessage::SendToLog()
    @     0x7f3e8d0577da  google::LogMessage::Flush()
    @     0x7f3e8d05a8a9  google::LogMessageFatal::~LogMessageFatal()
    @           0x409224  yb::master::MasterMain()
    @     0x7f3e88cb0825  __libc_start_main
    @           0x4085d9  _start
    @              (nil)  (unknown)

```

#### Content of yugabeyted.log:

```
[yugabyted start] 2020-08-26 07:12:39,457 INFO:  | 0.0s | cmd = start using config file: /home/yugabyte/var/conf/yugabyted.conf (args.config=None)
[yugabyted start] 2020-08-26 07:12:39,458 INFO:  | 0.0s | Starting yugabyted...
[yugabyted start] 2020-08-26 07:12:39,460 INFO:  | 0.0s | yugabyted started running with PID 1.
[yugabyted start] 2020-08-26 07:12:39,465 INFO:  | 0.0s | Running the post-installation script /home/yugabyte/bin/post_install.sh (may be a no-op)
[yugabyted start] 2020-08-26 07:12:39,472 INFO:  | 0.1s | Successfully ran the post-installation script.
[yugabyted start] 2020-08-26 07:12:39,474 INFO:  | 0.1s | About to start master with cmd /home/yugabyte/bin/yb-master --stop_on_parent_termination --undefok=stop_on_parent_termination --fs_data_dirs=/home/yugabyte/var/data --webserver_interface=0.0.0.0 --metrics_snapshotter_tserver_metrics_whitelist=handler_latency_yb_tserver_TabletServerService_Read_count,handler_latency_yb_tserver_TabletServerService_Write_count,handler_latency_yb_tserver_TabletServerService_Read_sum,handler_latency_yb_tserver_TabletServerService_Write_sum,disk_usage,cpu_usage,node_up --yb_num_shards_per_tserver=1 --ysql_num_shards_per_tserver=1 --cluster_uuid=e4d92bec-dabc-4206-8452-19f24958e6f6 --rpc_bind_addresses=127.0.0.1:7100 --server_broadcast_addresses=127.0.0.1:7100 --replication_factor=1 --use_initial_sys_catalog_snapshot --server_dump_info_path=/home/yugabyte/var/data/master-info --master_enable_metrics_snapshotter=true --webserver_port=7000 --default_memory_limit_to_ram_ratio=0.35 --instance_uuid_override=868880d54b134090afae97dde5d318fb --master_addresses=127.0.0.1:7100
[yugabyted start] 2020-08-26 07:12:39,480 INFO:  | 0.1s | master started running with PID 15.
[yugabyted start] 2020-08-26 07:12:39,505 INFO:  | 0.1s | Querying for all masters in cluster
[yugabyted start] 2020-08-26 07:12:39,506 INFO:  | 0.1s | Waiting to get the full master addrs list from master
[yugabyted start] 2020-08-26 07:12:39,506 INFO:  | 0.1s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:12:39,604 INFO:  | 0.2s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:12:39,605 INFO:  | 0.2s | Got all masters: []
[yugabyted start] 2020-08-26 07:12:40,106 INFO:  | 0.7s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:12:40,187 INFO:  | 0.8s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:12:40,188 INFO:  | 0.8s | Got all masters: []
[yugabyted start] 2020-08-26 07:12:40,689 INFO:  | 1.3s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:12:40,776 INFO:  | 1.4s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:12:40,777 INFO:  | 1.4s | Got all masters: []
[yugabyted start] 2020-08-26 07:12:41,278 INFO:  | 1.9s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:12:41,374 INFO:  | 2.0s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:12:41,375 INFO:  | 2.0s | Got all masters: []
[yugabyted start] 2020-08-26 07:12:41,876 INFO:  | 2.5s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:12:42,002 INFO:  | 2.6s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:12:42,002 INFO:  | 2.6s | Got all masters: []
[yugabyted start] 2020-08-26 07:12:42,504 INFO:  | 3.1s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:12:42,628 INFO:  | 3.2s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:12:42,629 INFO:  | 3.2s | Got all masters: []
[yugabyted start] 2020-08-26 07:12:43,130 INFO:  | 3.7s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:12:43,225 INFO:  | 3.8s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:12:43,226 INFO:  | 3.8s | Got all masters: []
[yugabyted start] 2020-08-26 07:12:43,727 INFO:  | 4.3s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:12:43,840 INFO:  | 4.4s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:12:43,841 INFO:  | 4.4s | Got all masters: []
[yugabyted start] 2020-08-26 07:12:44,342 INFO:  | 4.9s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:12:44,482 INFO:  | 5.1s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:12:44,483 INFO:  | 5.1s | Got all masters: []
[yugabyted start] 2020-08-26 07:12:44,984 INFO:  | 5.6s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:12:45,122 INFO:  | 5.7s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:12:45,122 INFO:  | 5.7s | Got all masters: []
[yugabyted start] 2020-08-26 07:12:45,623 INFO:  | 6.2s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:12:45,719 INFO:  | 6.3s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:12:45,719 INFO:  | 6.3s | Got all masters: []
[yugabyted start] 2020-08-26 07:12:46,220 INFO:  | 6.8s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:12:46,299 INFO:  | 6.9s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:12:46,300 INFO:  | 6.9s | Got all masters: []
[yugabyted start] 2020-08-26 07:12:46,801 INFO:  | 7.4s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:12:46,928 INFO:  | 7.5s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:12:46,929 INFO:  | 7.5s | Got all masters: []
[yugabyted start] 2020-08-26 07:12:47,430 INFO:  | 8.0s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:12:47,551 INFO:  | 8.1s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:12:47,552 INFO:  | 8.1s | Got all masters: []
[yugabyted start] 2020-08-26 07:12:48,053 INFO:  | 8.6s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:12:48,178 INFO:  | 8.8s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:12:48,179 INFO:  | 8.8s | Got all masters: []
[yugabyted start] 2020-08-26 07:12:48,680 INFO:  | 9.3s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:12:48,805 INFO:  | 9.4s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:12:48,805 INFO:  | 9.4s | Got all masters: []
[yugabyted start] 2020-08-26 07:12:49,306 INFO:  | 9.9s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:12:49,435 INFO:  | 10.0s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:12:49,435 INFO:  | 10.0s | Got all masters: []
[yugabyted start] 2020-08-26 07:12:49,937 INFO:  | 10.5s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:12:50,073 INFO:  | 10.7s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:12:50,074 INFO:  | 10.7s | Got all masters: []
[yugabyted start] 2020-08-26 07:12:50,575 INFO:  | 11.2s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:12:50,710 INFO:  | 11.3s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:12:50,710 INFO:  | 11.3s | Got all masters: []
[yugabyted start] 2020-08-26 07:12:51,212 INFO:  | 11.8s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:12:51,336 INFO:  | 11.9s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:12:51,337 INFO:  | 11.9s | Got all masters: []
[yugabyted start] 2020-08-26 07:12:51,838 INFO:  | 12.4s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:12:51,960 INFO:  | 12.5s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:12:51,960 INFO:  | 12.5s | Got all masters: []
[yugabyted start] 2020-08-26 07:12:52,462 INFO:  | 13.0s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:12:52,591 INFO:  | 13.2s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:12:52,591 INFO:  | 13.2s | Got all masters: []
[yugabyted start] 2020-08-26 07:12:53,093 INFO:  | 13.7s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:12:53,232 INFO:  | 13.8s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:12:53,232 INFO:  | 13.8s | Got all masters: []
[yugabyted start] 2020-08-26 07:12:53,733 INFO:  | 14.3s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:12:53,836 INFO:  | 14.4s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:12:53,836 INFO:  | 14.4s | Got all masters: []
[yugabyted start] 2020-08-26 07:12:54,337 INFO:  | 14.9s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:12:54,467 INFO:  | 15.0s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:12:54,467 INFO:  | 15.0s | Got all masters: []
[yugabyted start] 2020-08-26 07:12:54,968 INFO:  | 15.6s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:12:55,116 INFO:  | 15.7s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:12:55,117 INFO:  | 15.7s | Got all masters: []
[yugabyted start] 2020-08-26 07:12:55,618 INFO:  | 16.2s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:12:55,726 INFO:  | 16.3s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:12:55,726 INFO:  | 16.3s | Got all masters: []
[yugabyted start] 2020-08-26 07:12:56,227 INFO:  | 16.8s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:12:56,346 INFO:  | 16.9s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:12:56,346 INFO:  | 16.9s | Got all masters: []
[yugabyted start] 2020-08-26 07:12:56,848 INFO:  | 17.4s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:12:56,998 INFO:  | 17.6s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:12:56,999 INFO:  | 17.6s | Got all masters: []
[yugabyted start] 2020-08-26 07:12:57,500 INFO:  | 18.1s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:12:57,584 INFO:  | 18.2s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:12:57,584 INFO:  | 18.2s | Got all masters: []
[yugabyted start] 2020-08-26 07:12:58,086 INFO:  | 18.7s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:12:58,203 INFO:  | 18.8s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:12:58,203 INFO:  | 18.8s | Got all masters: []
[yugabyted start] 2020-08-26 07:12:58,704 INFO:  | 19.3s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:12:58,812 INFO:  | 19.4s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:12:58,813 INFO:  | 19.4s | Got all masters: []
[yugabyted start] 2020-08-26 07:12:59,314 INFO:  | 19.9s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:12:59,452 INFO:  | 20.0s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:12:59,453 INFO:  | 20.0s | Got all masters: []
[yugabyted start] 2020-08-26 07:12:59,954 INFO:  | 20.5s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:13:00,096 INFO:  | 20.7s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:13:00,096 INFO:  | 20.7s | Got all masters: []
[yugabyted start] 2020-08-26 07:13:00,598 INFO:  | 21.2s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:13:00,730 INFO:  | 21.3s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:13:00,731 INFO:  | 21.3s | Got all masters: []
[yugabyted start] 2020-08-26 07:13:01,232 INFO:  | 21.8s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:13:01,353 INFO:  | 21.9s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:13:01,353 INFO:  | 21.9s | Got all masters: []
[yugabyted start] 2020-08-26 07:13:01,855 INFO:  | 22.4s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:13:01,980 INFO:  | 22.6s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:13:01,981 INFO:  | 22.6s | Got all masters: []
[yugabyted start] 2020-08-26 07:13:02,482 INFO:  | 23.1s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:13:02,608 INFO:  | 23.2s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:13:02,608 INFO:  | 23.2s | Got all masters: []
[yugabyted start] 2020-08-26 07:13:03,110 INFO:  | 23.7s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:13:03,225 INFO:  | 23.8s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:13:03,226 INFO:  | 23.8s | Got all masters: []
[yugabyted start] 2020-08-26 07:13:03,727 INFO:  | 24.3s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:13:03,836 INFO:  | 24.4s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:13:03,836 INFO:  | 24.4s | Got all masters: []
[yugabyted start] 2020-08-26 07:13:04,338 INFO:  | 24.9s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:13:04,467 INFO:  | 25.0s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:13:04,467 INFO:  | 25.0s | Got all masters: []
[yugabyted start] 2020-08-26 07:13:04,968 INFO:  | 25.6s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:13:05,122 INFO:  | 25.7s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:13:05,123 INFO:  | 25.7s | Got all masters: []
[yugabyted start] 2020-08-26 07:13:05,624 INFO:  | 26.2s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:13:05,732 INFO:  | 26.3s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:13:05,732 INFO:  | 26.3s | Got all masters: []
[yugabyted start] 2020-08-26 07:13:06,233 INFO:  | 26.8s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:13:06,331 INFO:  | 26.9s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:13:06,331 INFO:  | 26.9s | Got all masters: []
[yugabyted start] 2020-08-26 07:13:06,833 INFO:  | 27.4s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:13:07,009 INFO:  | 27.6s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:13:07,010 INFO:  | 27.6s | Got all masters: []
[yugabyted start] 2020-08-26 07:13:07,512 INFO:  | 28.1s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:13:07,641 INFO:  | 28.2s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:13:07,641 INFO:  | 28.2s | Got all masters: []
[yugabyted start] 2020-08-26 07:13:08,142 INFO:  | 28.7s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:13:08,263 INFO:  | 28.8s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:13:08,264 INFO:  | 28.8s | Got all masters: []
[yugabyted start] 2020-08-26 07:13:08,765 INFO:  | 29.3s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:13:08,933 INFO:  | 29.5s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:13:08,933 INFO:  | 29.5s | Got all masters: []
[yugabyted start] 2020-08-26 07:13:09,435 INFO:  | 30.0s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:13:09,575 INFO:  | 30.2s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:13:09,575 INFO:  | 30.2s | Got all masters: []
[yugabyted start] 2020-08-26 07:13:10,077 INFO:  | 30.7s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:13:10,202 INFO:  | 30.8s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:13:10,202 INFO:  | 30.8s | Got all masters: []
[yugabyted start] 2020-08-26 07:13:10,703 INFO:  | 31.3s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:13:10,808 INFO:  | 31.4s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:13:10,809 INFO:  | 31.4s | Got all masters: []
[yugabyted start] 2020-08-26 07:13:11,310 INFO:  | 31.9s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:13:11,427 INFO:  | 32.0s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:13:11,428 INFO:  | 32.0s | Got all masters: []
[yugabyted start] 2020-08-26 07:13:11,929 INFO:  | 32.5s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:13:12,078 INFO:  | 32.7s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:13:12,079 INFO:  | 32.7s | Got all masters: []
[yugabyted start] 2020-08-26 07:13:12,580 INFO:  | 33.2s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:13:12,676 INFO:  | 33.3s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:13:12,677 INFO:  | 33.3s | Got all masters: []
[yugabyted start] 2020-08-26 07:13:13,178 INFO:  | 33.8s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:13:13,300 INFO:  | 33.9s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:13:13,300 INFO:  | 33.9s | Got all masters: []
[yugabyted start] 2020-08-26 07:13:13,801 INFO:  | 34.4s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:13:13,923 INFO:  | 34.5s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:13:13,924 INFO:  | 34.5s | Got all masters: []
[yugabyted start] 2020-08-26 07:13:14,425 INFO:  | 35.0s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:13:14,620 INFO:  | 35.2s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:13:14,621 INFO:  | 35.2s | Got all masters: []
[yugabyted start] 2020-08-26 07:13:15,122 INFO:  | 35.7s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:13:15,250 INFO:  | 35.8s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:13:15,251 INFO:  | 35.8s | Got all masters: []
[yugabyted start] 2020-08-26 07:13:15,752 INFO:  | 36.3s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:13:15,881 INFO:  | 36.5s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:13:15,882 INFO:  | 36.5s | Got all masters: []
[yugabyted start] 2020-08-26 07:13:16,383 INFO:  | 37.0s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:13:16,475 INFO:  | 37.1s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:13:16,476 INFO:  | 37.1s | Got all masters: []
[yugabyted start] 2020-08-26 07:13:16,977 INFO:  | 37.6s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:13:17,097 INFO:  | 37.7s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:13:17,097 INFO:  | 37.7s | Got all masters: []
[yugabyted start] 2020-08-26 07:13:17,598 INFO:  | 38.2s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:13:17,756 INFO:  | 38.3s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:13:17,756 INFO:  | 38.3s | Got all masters: []
[yugabyted start] 2020-08-26 07:13:18,258 INFO:  | 38.8s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:13:18,391 INFO:  | 39.0s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:13:18,392 INFO:  | 39.0s | Got all masters: []
[yugabyted start] 2020-08-26 07:13:18,893 INFO:  | 39.5s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:13:18,975 INFO:  | 39.6s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:13:18,975 INFO:  | 39.6s | Got all masters: []
[yugabyted start] 2020-08-26 07:13:19,477 INFO:  | 40.1s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:13:19,606 INFO:  | 40.2s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:13:19,606 INFO:  | 40.2s | Got all masters: []
[yugabyted start] 2020-08-26 07:13:20,108 INFO:  | 40.7s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:13:20,271 INFO:  | 40.9s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:13:20,272 INFO:  | 40.9s | Got all masters: []
[yugabyted start] 2020-08-26 07:13:20,773 INFO:  | 41.4s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:13:20,939 INFO:  | 41.5s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:13:20,939 INFO:  | 41.5s | Got all masters: []
[yugabyted start] 2020-08-26 07:13:21,441 INFO:  | 42.0s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:13:21,573 INFO:  | 42.2s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:13:21,573 INFO:  | 42.2s | Got all masters: []
[yugabyted start] 2020-08-26 07:13:22,075 INFO:  | 42.7s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:13:22,195 INFO:  | 42.8s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:13:22,196 INFO:  | 42.8s | Got all masters: []
[yugabyted start] 2020-08-26 07:13:22,697 INFO:  | 43.3s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:13:22,824 INFO:  | 43.4s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:13:22,825 INFO:  | 43.4s | Got all masters: []
[yugabyted start] 2020-08-26 07:13:23,326 INFO:  | 43.9s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:13:23,445 INFO:  | 44.0s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:13:23,445 INFO:  | 44.0s | Got all masters: []
[yugabyted start] 2020-08-26 07:13:23,947 INFO:  | 44.5s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:13:24,070 INFO:  | 44.7s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:13:24,070 INFO:  | 44.7s | Got all masters: []
[yugabyted start] 2020-08-26 07:13:24,571 INFO:  | 45.2s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:13:24,685 INFO:  | 45.3s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:13:24,685 INFO:  | 45.3s | Got all masters: []
[yugabyted start] 2020-08-26 07:13:25,186 INFO:  | 45.8s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:13:25,267 INFO:  | 45.8s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:13:25,267 INFO:  | 45.8s | Got all masters: []
[yugabyted start] 2020-08-26 07:13:25,768 INFO:  | 46.4s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:13:25,847 INFO:  | 46.4s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:13:25,847 INFO:  | 46.4s | Got all masters: []
[yugabyted start] 2020-08-26 07:13:26,349 INFO:  | 46.9s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:13:26,470 INFO:  | 47.1s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:13:26,470 INFO:  | 47.1s | Got all masters: []
[yugabyted start] 2020-08-26 07:13:26,971 INFO:  | 47.6s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:13:27,122 INFO:  | 47.7s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:13:27,122 INFO:  | 47.7s | Got all masters: []
[yugabyted start] 2020-08-26 07:13:27,624 INFO:  | 48.2s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:13:27,712 INFO:  | 48.3s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:13:27,713 INFO:  | 48.3s | Got all masters: []
[yugabyted start] 2020-08-26 07:13:28,214 INFO:  | 48.8s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:13:28,302 INFO:  | 48.9s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:13:28,302 INFO:  | 48.9s | Got all masters: []
[yugabyted start] 2020-08-26 07:13:28,803 INFO:  | 49.4s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:13:28,939 INFO:  | 49.5s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:13:28,939 INFO:  | 49.5s | Got all masters: []
[yugabyted start] 2020-08-26 07:13:29,441 INFO:  | 50.0s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:13:29,592 INFO:  | 50.2s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:13:29,592 INFO:  | 50.2s | Got all masters: []
[yugabyted start] 2020-08-26 07:13:30,093 INFO:  | 50.7s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:13:30,238 INFO:  | 50.8s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:13:30,238 INFO:  | 50.8s | Got all masters: []
[yugabyted start] 2020-08-26 07:13:30,739 INFO:  | 51.3s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:13:30,906 INFO:  | 51.5s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:13:30,906 INFO:  | 51.5s | Got all masters: []
[yugabyted start] 2020-08-26 07:13:31,407 INFO:  | 52.0s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:13:31,486 INFO:  | 52.1s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:13:31,486 INFO:  | 52.1s | Got all masters: []
[yugabyted start] 2020-08-26 07:13:31,987 INFO:  | 52.6s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:13:32,094 INFO:  | 52.7s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:13:32,094 INFO:  | 52.7s | Got all masters: []
[yugabyted start] 2020-08-26 07:13:32,596 INFO:  | 53.2s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:13:32,703 INFO:  | 53.3s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:13:32,704 INFO:  | 53.3s | Got all masters: []
[yugabyted start] 2020-08-26 07:13:33,205 INFO:  | 53.8s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:13:33,325 INFO:  | 53.9s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:13:33,325 INFO:  | 53.9s | Got all masters: []
[yugabyted start] 2020-08-26 07:13:33,826 INFO:  | 54.4s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:13:33,965 INFO:  | 54.5s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:13:33,965 INFO:  | 54.5s | Got all masters: []
[yugabyted start] 2020-08-26 07:13:34,466 INFO:  | 55.0s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:13:34,597 INFO:  | 55.2s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:13:34,598 INFO:  | 55.2s | Got all masters: []
[yugabyted start] 2020-08-26 07:13:35,099 INFO:  | 55.7s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:13:35,251 INFO:  | 55.8s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:13:35,252 INFO:  | 55.8s | Got all masters: []
[yugabyted start] 2020-08-26 07:13:35,753 INFO:  | 56.3s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:13:35,920 INFO:  | 56.5s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:13:35,921 INFO:  | 56.5s | Got all masters: []
[yugabyted start] 2020-08-26 07:13:36,422 INFO:  | 57.0s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:13:36,519 INFO:  | 57.1s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:13:36,520 INFO:  | 57.1s | Got all masters: []
[yugabyted start] 2020-08-26 07:13:37,021 INFO:  | 57.6s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:13:37,103 INFO:  | 57.7s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:13:37,104 INFO:  | 57.7s | Got all masters: []
[yugabyted start] 2020-08-26 07:13:37,605 INFO:  | 58.2s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:13:37,712 INFO:  | 58.3s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:13:37,712 INFO:  | 58.3s | Got all masters: []
[yugabyted start] 2020-08-26 07:13:38,214 INFO:  | 58.8s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:13:38,382 INFO:  | 59.0s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:13:38,383 INFO:  | 59.0s | Got all masters: []
[yugabyted start] 2020-08-26 07:13:38,884 INFO:  | 59.5s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:13:39,074 INFO:  | 59.7s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:13:39,075 INFO:  | 59.7s | Got all masters: []
[yugabyted start] 2020-08-26 07:13:39,576 INFO:  | 60.2s | run_process: cmd: [u'/home/yugabyte/bin/yb-admin', u'--init_master_addrs', u'127.0.0.1:7100', u'list_all_masters']
[yugabyted start] 2020-08-26 07:13:39,705 INFO:  | 60.3s | run_process returned 1: 
OUT >>

<< ERR >>
<<
[yugabyted start] 2020-08-26 07:13:39,706 INFO:  | 60.3s | Got all masters: []
[yugabyted start] 2020-08-26 07:13:39,707 ERROR:  | 60.3s | Failed to query for all masters. Exception: Traceback (most recent call last):
  File "bin/yugabyted", line 826, in wait_get_all_masters
    return retry_op(self.get_all_masters, timeout)
  File "bin/yugabyted", line 2284, in retry_op
    now - start_time))
RuntimeError: Failed after retrying operation for 60.2000081539 secs.

For more information, check the logs in /home/yugabyte/var/logs
[yugabyted start] 2020-08-26 07:13:39,707 INFO:  | 60.3s | Shutting down...
[yugabyted start] 2020-08-26 07:13:39,713 INFO:  | 60.3s | yugabyted may not have terminated properly... Please check PGID 1.


```

**Comment by tedyu** [comment]
```
Fatal failure details written to /home/yugabyte/var/data/yb-data/master/logs/yb-master.FATAL.details.2020-08-26T07_12_39.pid15.txt
```
If the above file still exists, can you attach it here ?

thanks

**Comment by iSignal** [comment]
@walter-weinmann : What happens if you specify a different (clean) volume mount? Does the database start correctly in that case?

**Comment by walter-weinmann** [comment]
> @walter-weinmann : What happens if you specify a different (clean) volume mount? Does the database start correctly in that case?

#### It always starts with a clean volume:

```
rd /q /s tmp\yb_data 2>nul
md tmp\yb_data

docker run -d ^
           --name db_seeder_db ^
           -p     5433:5433 ^
           -p     7000:7000 ^
           -p     9000:9000 ^
           -p     9042:9042 ^
           -v     %cd%/tmp/yb_data:/home/yugabyte/var ^
           yugabytedb/yugabyte:%DB_SEEDER_VERSION% bin/yugabyted start --daemon=false

```

**Comment by walter-weinmann** [comment]
> ```
> Fatal failure details written to /home/yugabyte/var/data/yb-data/master/logs/yb-master.FATAL.details.2020-08-26T07_12_39.pid15.txt
> ```
> 
> If the above file still exists, can you attach it here ?
> 
> thanks

#### This file was never created:

![image](https://user-images.githubusercontent.com/1956149/91529166-1c7aaa80-e909-11ea-83ea-3e67d7d75cbd.png)

**Comment by walter-weinmann** [comment]
Is there any progress on this issue?

**Comment by walter-weinmann** [comment]
What can I do to help solve this problem?

**Comment by walter-weinmann** [comment]
Is there any plan to solve this problem?

**Comment by iSignal** [comment]
@walter-weinmann : The error you pasted in https://github.com/yugabyte/yugabyte-db/issues/5497#issue-686085399 sometimes happens when there is existing data in the volume mount, so I am surprised you saw this with a clean mount. 

@rao-vasireddy : Can you please run the yugabyted docker command 
```
md tmp\yb_data
docker run -it --name yugabyte -p7000:7000 -p9001:9000 -p5433:5433 -p9042:9042 -v %cd%/tmp/yb_data:/home/yugabyte/var yugabytedb/yugabyte:latest bin/yugabyted start --daemon=false
```
on a Windows laptop/desktop please, in case we can reproduce the problem on our side?

**Comment by walter-weinmann** [comment]
**Here is the result:**

```
D:\SoftDevelopment\Projects\Konnexions\db_seeder>md tmp\yb_data

D:\SoftDevelopment\Projects\Konnexions\db_seeder>docker run -it --name yugabyte -p7000:7000 -p9001:9000 -p5433:5433 -p9042:9042 -v %cd%/tmp/yb_data:/home/yugabyte/var yugabytedb/yugabyte:latest bin/yugabyted start --daemon=false
Unable to find image 'yugabytedb/yugabyte:latest' locally
latest: Pulling from yugabytedb/yugabyte
524b0c1e57f8: Pull complete
b5318e0f4ff7: Pull complete
ca1b70db4153: Pull complete
7bba4988270c: Pull complete
a804e7bfea89: Pull complete
5beb1bfc1b4f: Pull complete
Digest: sha256:eb4c9adc98d0837708d48ec9c550a99f7fa324e2999bd8f6de807a5d835e7ee9
Status: Downloaded newer image for yugabytedb/yugabyte:latest
Starting yugabyted...
/ Running system checks...Failed to setup master. Exception: Traceback (most recent call last):
  File "bin/yugabyted", line 883, in setup_master
    if retry_op(self.wait_master, timeout):
  File "bin/yugabyted", line 2450, in retry_op
    return func()
  File "bin/yugabyted", line 840, in wait_master
    raise RuntimeError("process died unexpectedly.")
RuntimeError: process died unexpectedly.

For more information, check the logs in /home/yugabyte/var/logs

D:\SoftDevelopment\Projects\Konnexions\db_seeder>

```

**Comment by walter-weinmann** [comment]
Still the same problem with Docker image version  `docker pull yugabytedb/yugabyte:2.3.3.0-b106`:

```
Starting yugabyted...,

/ Running system checks...
- Running system checks...
\ Running system checks...
| Running system checks...
/ Running system checks...
- Running system checks...
\ Running system checks...
| Running system checks...
/ Running system checks...
- Running system checks...
\ Running system checks...
| Running system checks...
/ Running system checks...
- Running system checks...
\ Running system checks...
| Running system checks...
/ Running system checks...
- Running system checks...
\ Running system checks...
| Running system checks...
/ Running system checks...
- Running system checks...
\ Running system checks...
| Running system checks...
```

**Comment by walter-weinmann** [comment]
Still the same problem with Docker image version docker pull yugabytedb/yugabyte:2.5.1.0-b153

**Comment by walter-weinmann** [comment]
Problem solved with version 2.5.2.0-b104 - thanks a lot.

**Comment by alidehghan** [comment]
**I downloaded latest docker version and the error still exists:**
I am running container on Windows11


```

F0207 12:24:03.478148    18 master_main.cc:155] Not found (yb/util/env_posix.cc:1496): Unable to initialize catalog manager: Failed to initialize sys tables async: Encountered errors during system catalog initialization:
	Error on Load: Not found (yb/util/env_posix.cc:1496): Could not load Raft group metadata from /home/yugabyte/yb_data/data/yb-data/master/tablet-meta/00000000000000000000000000000000: /home/yugabyte/yb_data/data/yb-data/master/tablet-meta/00000000000000000000000000000000: No such file or directory (system error 2)
	Error on CreateNew: : Failed to open new log: /home/yugabyte/yb_data/data/yb-data/master/wals/table-sys.catalog.uuid/tablet-00000000000000000000000000000000/wal-000000001: No such file or directory (system error 2)
Fatal failure details written to /home/yugabyte/yb_data/data/yb-data/master/logs/yb-master.FATAL.details.2022-02-07T12_24_03.pid18.txt
F20220207 12:24:03 ../../src/yb/master/master_main.cc:155] Not found (yb/util/env_posix.cc:1496): Unable to initialize catalog manager: Failed to initialize sys tables async: Encountered errors during system catalog initialization:
	Error on Load: Not found (yb/util/env_posix.cc:1496): Could not load Raft group metadata from /home/yugabyte/yb_data/data/yb-data/master/tablet-meta/00000000000000000000000000000000: /home/yugabyte/yb_data/data/yb-data/master/tablet-meta/00000000000000000000000000000000: No such file or directory (system error 2)
	Error on CreateNew: : Failed to open new log: /home/yugabyte/yb_data/data/yb-data/master/wals/table-sys.catalog.uuid/tablet-00000000000000000000000000000000/wal-000000001: No such file or directory (system error 2)
    @     0x7f3a577cf35c  yb::LogFatalHandlerSink::send()
    @     0x7f3a56bcdfde  google::LogMessage::SendToLog()
    @     0x7f3a56bcb16a  google::LogMessage::Flush()
    @     0x7f3a56bce859  google::LogMessageFatal::~LogMessageFatal()
    @           0x407083  yb::master::MasterMain()
    @     0x7f3a52231825  __libc_start_main
    @           0x4066d9  _start
    @              (nil)  (unknown)

```
