### ISSUE TITLE
[YW Platform] Enabling backup method in testupgrade throws exception for 2.0.9.0_13 and 2.2.7.0_5 configs

### ISSUE THREAD

**Issue by nmantrav2** [yugabyte/yugabyte-db#9270]
Repro steps:

1. Enable backup method in testupgrade itest
2. Test fails for 

-- 2.0.9.0_13 config with following exception

 Create backups : >>> Integration Test Failed <<<
51215 wait_for_task: Failed task with errors in 120.24636673927307s:
51216 Failed to execute task {"errorString":null,"nodeExporterUser":"prometheus","deviceInfo":null,"un      iverseUUID":"b71658b1-5529-4a40-855b-acb7315453c2","expectedUniverseVersion":0,"cmkArn":null,"en      cryptionAtRestConfig":{"encr..., hit error java.lang.RuntimeException: java.lang.RuntimeException: {"error": "Exception: Command '['ssh', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHost      sFile=/dev/null', '-i', '/opt/yugabyte/yugaware/data/keys/1fa4e623-8edb-4a77-8678-fb6a8f53c203/yb-itest-21289660d8-20210712-184619_1fa4e623-8edb-4a77-8678-fb6a8f53c203-key.pem', '-p', '54422',       '-q', 'yugabyte@172.151.25.97', \"cd / &&  bash -c '/home/yugabyte/master/bin/yb-admin --master      _addresses 172.151.25.97:7100,172.151.46.184:7100,172.151.49.130:7100 ysql_catalog_version'\"]'       returned non-zero exit status 1"}.

-- 2.2.7.0_5  with following exception

Create backups : >>> Integration Test Failed <<<
51327 wait_for_task: Failed task with errors in 30.168999195098877s:
51328 Failed to execute task {"errorString":null,"nodeExporterUser":"prometheus","deviceInfo":null,"un      iverseUUID":"cb7b70f3-2cf4-421b-a3ad-fe2e7e8ca5f8","expectedUniverseVersion":0,"cmkArn":null,"en      cryptionAtRestConfig":{"encr..., hit error java.lang.RuntimeException: java.lang.RuntimeExceptio      n: {"error": "Exception: 'namespace_name'"}.

**Comment by hsiaosu-yb** [comment]
Is this a consistent failure?
Which version of platform is this failure happening?  2.7, 2.6, etc?

**Comment by hsiaosu-yb** [comment]
More info from nmantrav2, these are consistent failures in 2.7.2 and 2.6 versions of platform.  After fixing these, we should probably re-enable these tests.

**Comment by OlegLoginov** [comment]
Fixed by the commit in the `master` branch: https://github.com/yugabyte/yugabyte-db/commit/e8c72f30f991553834936259cffdc7f904bfc879

**Comment by Arpit-yb** [comment]
its still failing on master - https://jenkins.dev.yugabyte.com/view/Test%20Jobs/job/itest-developer/2182/

**Comment by Arpit-yb** [comment]
CC: @nmantrav2 @VijiYB Can we prioritize this issue, since its been failing for quite some time now.
