### ISSUE TITLE
[YSQL] Stack trace shows up unexpectedly when running yugabyte.

### ISSUE THREAD

**Issue by nocaway** [yugabyte/yugabyte-db#9792]
Jira Link: [DB-4795](https://yugabyte.atlassian.net/browse/DB-4795)
The following stack trace logging message shows up when running YSQL.  Reported by @ajcaldera1 .

its pretty regular and always from the same thread-id
```
I0820 15:54:57.596720  1118 pggate.cc:152] Reset YSQL bind address to yb-tserver-1.yb-tservers.yb-dev-yb-can-poc-us-central1-b.svc.cluster.local:5432
I0820 15:54:57.596953  1118 server_base_options.cc:137] Updating master addrs to {yb-master-0.yb-masters.yb-dev-yb-can-poc-us-central1-c.svc.cluster.local:7100},{yb-master-0.yb-masters.yb-dev-yb-can-poc-us-central1-b.svc.cluster.local:7100},{yb-master-0.yb-masters.yb-dev-yb-can-poc-us-central1-f.svc.cluster.local:7100}
I0820 15:54:57.597149  1118 mem_tracker.cc:282] MemTracker: hard memory limit is 54.375000 GB
I0820 15:54:57.597167  1118 mem_tracker.cc:284] MemTracker: soft memory limit is 46.218750 GB
I0820 15:54:57.598192  1118 thread_pool.cc:171] Starting thread pool { name: pggate_ybclient queue_limit: 10000 max_workers: 1024 }
```

```
W0820 16:39:49.369221  1118 session.cc:323] Client writing with no deadline set, using 60 seconds.
    @     0x7f2afbc28227  yb::client::YBSession::Batcher()
    @     0x7f2afbc28341  yb::client::YBSession::Apply()
    @     0x7f2b01254183  yb::pggate::PgSession::RunHelper::Apply()
    @     0x7f2b0127686d  yb::pggate::PgDocOp::SendRequestImpl()
    @     0x7f2b0127489e  yb::pggate::PgDocOp::SendRequest()
    @     0x7f2b01274922  yb::pggate::PgDocOp::Execute()
    @     0x7f2b0126b35f  yb::pggate::PgDmlRead::Exec()
    @     0x7f2b01264b79  yb::pggate::PgDml::ProcessSecondaryIndexRequest()
    @     0x7f2b0126b2d8  yb::pggate::PgDmlRead::Exec()
    @     0x7f2b0124106f  yb::pggate::PgApiImpl::ExecSelect()
    @     0x7f2b0123a652  YBCPgExecSelect
    @           0x5550fd  ybc_getnext_heaptuple
    @           0x556289  ybcingettuple
    @           0x4f8a75  index_getnext_tid
    @           0x4f8cf4  index_getnext
    @           0x6e40bc  IndexNext
    @           0x6cce81  ExecScan
    @           0x6efd3e  ExecNestLoop
    @           0x6f2ab6  ExecSort
    @           0x6c1e8b  standard_ExecutorRun
    @     0x7f2af306789d  pgss_ExecutorRun
    @     0x7f2af2e6056a  ybpgm_ExecutorRun
    @           0x8767ab  PortalRunSelect
    @           0x878291  PortalRun
    @           0x8721e8  yb_exec_execute_message
    @           0x8751a3  PostgresMain
    @           0x49af59  ServerLoop
    @           0x7dbd1f  PostmasterMain
    @           0x727aaa  PostgresServerProcessMain
    @           0x727ca9  main
    @     0x7f2affc94825  __libc_start_main
    @           0x49d509  _start
```

**Comment by nocaway** [comment]
The message started showing up after the commit
https://github.com/yugabyte/yugabyte-db/commit/990f754698ef14a97d62b7eb74b2d09fb3c8be32

**Comment by m-iancu** [comment]
This is a warning when deadline was not set correctly for the session. Could not find it in recent clusters so assuming it is fixed (for instance this change fixes it for CDC: https://github.com/yugabyte/yugabyte-db/commit/9552f1e1446f76ac07925601efe06064385f773a).

**Comment by NatashaSerebryanaya** [comment]
This warning still shows up in a lot of tests. 
One can see them in https://detective.dev.yugabyte.com/?commits=23babb366d63deaa60e0eef8a34df6742457a312
In all CDCSDKYsqlTest tests (failing or not)
org.yb.cdc.ysql.TestDDL#testRenameTable, org.yb.cdc.ysql.Test3IntCol#testLongRunningScript ...

It's very confusing to see a stack trace not related to the fail reason. And even more confusing to see it in the passed tests.

Should the tests be fixed somehow or it should be a code fix?

**Comment by qvad** [comment]
No longer observed in unit tests and other test pipelines.
